### ISSUE TITLE
Panic on flynn route (OSX)

### ISSUE THREAD

**Issue by kknight** [flynn/flynn#1025]
When trying to view routes the cli panics. Please let me know if you need any more info to resolve the issue.

```
$ flynn route
ROUTE  SERVICE  ID
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xf5d27]

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc20803ca80, 0x0, 0x0, 0x0, 0x367de0, 0xc20802a050)
	/Users/titanous/src/gopkgs/src/github.com/flynn/flynn/pkg/shutdown/handler.go:65 +0x12e
github.com/flynn/flynn/pkg/shutdown.Exit()
	/Users/titanous/src/gopkgs/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x73
github.com/flynn/flynn/router/types.(*Route).HTTPRoute(0xc2080451d0, 0x4)
	/Users/titanous/src/gopkgs/src/github.com/flynn/flynn/router/types/types.go:31 +0x187
main.runRoute(0xc20802e9c0, 0xc208042570, 0x0, 0x0)
	/private/tmp/flynn-build/cli/route.go:77 +0x812
main.runCommand(0x7fff5fbffc96, 0x5, 0x5bad38, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/flynn-build/cli/main.go:169 +0x91f
main.main()
	/private/tmp/flynn-build/cli/main.go:108 +0xb48

goroutine 5 [syscall]:
os/signal.loop()
	/Users/titanous/src/go-tip/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/Users/titanous/src/go-tip/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc20803ca80)
	/Users/titanous/src/gopkgs/src/github.com/flynn/flynn/pkg/shutdown/handler.go:54 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/Users/titanous/src/gopkgs/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/titanous/src/go-tip/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [runnable]:
net/http.(*persistConn).readLoop(0xc208068000)
	/Users/titanous/src/go-tip/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/Users/titanous/src/go-tip/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc208068000)
	/Users/titanous/src/go-tip/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/Users/titanous/src/go-tip/src/net/http/transport.go:661 +0xcbc
```

**Comment by titanous** [comment]
I've released a fixed CLI. Run `flynn update` to get it.

**Comment by kknight** [comment]
Thanks. Works like a charm now!
