### ISSUE TITLE
Nil panic in SSE flush

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1263]
```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x635ada]

goroutine 28 [running]:
bufio.(*Writer).flush(0xc208159c80, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:530 +0xda
bufio.(*Writer).Flush(0xc208159c80, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:519 +0x3a
net/http.(*response).Flush(0xc20810f220)
	/usr/local/go/src/net/http/server.go:1047 +0x4c
github.com/flynn/flynn/pkg/httphelper.(*ResponseWriter).Flush(0xc208167b90)
	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/httphelper/response_writer.go:54 +0x6d
github.com/flynn/flynn/pkg/sse.(*writer).Flush(0xc208119c60)
	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/sse/sse.go:54 +0x6c
github.com/flynn/flynn/pkg/sse.(*Stream).sendKeepAlive(0xc208124a10, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/sse/stream.go:126 +0xc7
github.com/flynn/flynn/pkg/sse.func·002()
	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/sse/stream.go:86 +0x241
created by github.com/flynn/flynn/pkg/sse.(*Stream).Serve
	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/sse/stream.go:97 +0x509
```

https://s3.amazonaws.com/flynn-ci-logs/20150314172535-17cdc78e-build-5fd0d5fac00f1baec4124e602b88a3e030e8fe49-2015-03-14-17-41-36.txt

**Comment by lmars** [comment]
This was fixed by #1464 (the leaked SSE stream was trying to send a keep alive to a closed connection).
