### ISSUE TITLE
Bundler fatal error in ruby buildpack

### ISSUE THREAD

**Issue by jwaldrip** [flynn/flynn#1296]
Is there a buildpack with an updated version of bundler? I am getting these errors and cannot deploy my app... some light reading led me to believe that it had to do with parallel installation. This is a test on vagrant using flynn demo.

```
$ git push flynn master
Counting objects: 59771, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (23221/23221), done.
Writing objects: 100% (59771/59771), 87.95 MiB | 23.60 MiB/s, done.
Total 59771 (delta 39942), reused 54438 (delta 35218)
-----> Building boulder...
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.1
-----> Installing dependencies using 1.7.12
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching source index from https://code.stripe.com/
       Fetching source index from https://rubygems.org/
       Fetching git://github.com/brandfolder/bitly.git
       Fetching git://github.com/SamSaffron/memory_profiler.git
       Fetching git://github.com/RubyMoney/money.git
       Fetching source index from https://code.stripe.com/
       Using rake 10.4.2
       Installing CFPropertyList 2.3.0
       Installing minitest 5.5.1
       Installing json 1.8.2
       Unfortunately, a fatal error has occurred. Please see the Bundler
       troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/installer.rb:305:in `install_in_parallel': undefined method `[]' for nil:NilClass (NoMethodError)
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/installer.rb:88:in `run'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/installer.rb:18:in `install'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/cli/install.rb:79:in `run'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/cli.rb:145:in `install'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/command.rb:27:in `run'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor.rb:363:in `dispatch'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/base.rb:440:in `start'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/cli.rb:9:in `start'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/bin/bundle:20:in `block in <top (required)>'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/bin/bundle:18:in `<top (required)>'
       from vendor/bundle/ruby/2.2.0/bin/bundle:19:in `load'
       from vendor/bundle/ruby/2.2.0/bin/bundle:19:in `<main>'
       Bundler Output: Fetching source index from https://code.stripe.com/
       Fetching source index from https://rubygems.org/
       Fetching git://github.com/brandfolder/bitly.git
       Fetching git://github.com/SamSaffron/memory_profiler.git
       Fetching git://github.com/RubyMoney/money.git
       Fetching source index from https://code.stripe.com/
       Using rake 10.4.2
       Installing CFPropertyList 2.3.0
       Installing minitest 5.5.1
       Installing json 1.8.2
       Unfortunately, a fatal error has occurred. Please see the Bundler
       troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
       /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/installer.rb:305:in `install_in_parallel': undefined method `[]' for nil:NilClass (NoMethodError)
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/installer.rb:88:in `run'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/installer.rb:18:in `install'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/cli/install.rb:79:in `run'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/cli.rb:145:in `install'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/command.rb:27:in `run'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor.rb:363:in `dispatch'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/vendor/thor/base.rb:440:in `start'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/cli.rb:9:in `start'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/bin/bundle:20:in `block in <top (required)>'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
       from /tmp/build/vendor/bundle/ruby/2.2.0/gems/bundler-1.7.12/bin/bundle:18:in `<top (required)>'
       from vendor/bundle/ruby/2.2.0/bin/bundle:19:in `load'
       from vendor/bundle/ruby/2.2.0/bin/bundle:19:in `<main>'
       !
       !     Failed to install gems via Bundler.
       !
remote: Build failed: exec: job exited with status 1
To ssh://git@demo.localflynn.com:2222/boulder.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@demo.localflynn.com:2222/boulder.git'
```

**Comment by titanous** [comment]
We're currently running heroku/heroku-buildpack-ruby@bac6cf09, which is the latest version. Do you have a Gemfile that can reproduce this error consistently?

**Comment by titanous** [comment]
It looks like this issue might be caused by insufficient memory. The worker change in Bundler v1.8.0 should remove the potential for this error (bundler/bundler#3063).

I've filed an upstream issue at heroku/heroku-buildpack-ruby#353 and will attempt to fork and update bundler myself if that doesn't work out.

**Comment by jwaldrip** [comment]
Here is the Gemfile:

https://gist.github.com/jwaldrip/ec279460c73667fa6046

**Comment by titanous** [comment]
This is purely a resource issue, bundler/ruby is *really* heavy with large Gemfiles.

I added this to my Vagrantfile and built a new VM, and your Gemfile worked just fine:

```ruby
  config.vm.provider "virtualbox" do |v, override|
    v.memory = 2048
    v.cpus = 4
  end
```

**Comment by titanous** [comment]
Hmm, after trying a few more times, it only works some of the time, I'll try modding the buildpack to only use one job.

**Comment by titanous** [comment]
This seems to work consistently:

```text
flynn env set BUILDPACK_URL=https://github.com/titanous/heroku-buildpack-ruby#one-job
```

Here's the patch: https://github.com/heroku/heroku-buildpack-ruby/commit/ff0045ff9cbeb3441008f0ecc22b712bb97c07ab

I'll try to send a patch upstream that makes the number of jobs configurable.

**Comment by titanous** [comment]
Sent heroku/heroku-buildpack-ruby#354 upstream.

**Comment by titanous** [comment]
I'm going to consider this resolved, upstream will not accept the patch, but the workaround is available on my fork and the future update to Bundler 1.9 will eliminate this issue.
