### ISSUE TITLE
pkg/cluster: attachClient.Write blocks indefinitely when the job fails

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1457]
CI is currently experiencing issues with the libvirt daemon restarting, leading to jobs failing to start (see #1451).

When this happens, `exex.Cmd.Run` blocks indefinitely.

For example, in [this CI failure](https://s3.amazonaws.com/flynn-ci-logs/20150415015803-1e17791e-build-8467e6cbd1d2eb7c50d368bb3ef392bd1a3294e8-2015-04-15-02-17-34.txt), `TestReleaseImages` timed out running `flynn-host update`, and the resulting `SIGQUIT` revealed the following blocked goroutines:

```
++ 02:13:38.299 goroutine 1 [semacquire, 7 minutes]:
++ 02:13:38.299 sync.(*Mutex).Lock(0xc2080c6d38)
++ 02:13:38.299 	/usr/local/go/src/sync/mutex.go:66 +0xd3
++ 02:13:38.299 github.com/flynn/flynn/pkg/cluster.(*attachClient).Close(0xc2080c6d20, 0x0, 0x0)
++ 02:13:38.299 	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/cluster/attach.go:253 +0x4a
++ 02:13:38.299 github.com/flynn/flynn/pkg/exec.(*Cmd).close(0xc208193e40)
++ 02:13:38.299 	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/exec/exec.go:275 +0x4b
++ 02:13:38.299 github.com/flynn/flynn/pkg/exec.(*Cmd).Wait(0xc208193e40, 0x0, 0x0)
++ 02:13:38.299 	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/exec/exec.go:301 +0x3b7
++ 02:13:38.299 github.com/flynn/flynn/pkg/exec.(*Cmd).Run(0xc208193e40, 0x0, 0x0)
++ 02:13:38.299 	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/exec/exec.go:317 +0x71
++ 02:13:38.299 github.com/flynn/flynn/host/cli.runUpdate(0xc2080d1320, 0x0, 0x0)
++ 02:13:38.299 	/home/ubuntu/go/src/github.com/flynn/flynn/host/cli/update.go:155 +0x21fb
++ 02:13:38.299 github.com/flynn/flynn/host/cli.Run(0x7fff1b14ee05, 0x6, 0xc20804f700, 0x4, 0x4, 0x0, 0x0)
++ 02:13:38.299 	/home/ubuntu/go/src/github.com/flynn/flynn/host/cli/cli.go:60 +0x6b3
++ 02:13:38.299 main.main()
++ 02:13:38.299 	/home/ubuntu/go/src/github.com/flynn/flynn/host/host.go:126 +0x8c1
...
++ 02:13:38.300 goroutine 55 [semacquire, 7 minutes]:
++ 02:13:38.300 sync.(*Mutex).Lock(0xc2080c6d38)
++ 02:13:38.300 	/usr/local/go/src/sync/mutex.go:66 +0xd3
++ 02:13:38.300 github.com/flynn/flynn/pkg/cluster.(*attachClient).Write(0xc2080c6d20, 0xc20813a000, 0x7a7, 0xe25, 0x0, 0x0, 0x0)
++ 02:13:38.300 	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/cluster/attach.go:205 +0x62
++ 02:13:38.300 bytes.(*Reader).WriteTo(0xc2080e10e0, 0x7fc3c5477dd8, 0xc2080c6d20, 0x7fc3c5477e00, 0x0, 0x0)
++ 02:13:38.300 	/usr/local/go/src/bytes/reader.go:131 +0xda
++ 02:13:38.300 io.Copy(0x7fc3c5477dd8, 0xc2080c6d20, 0x7fc3c5473380, 0xc2080e10e0, 0x0, 0x0, 0x0)
++ 02:13:38.300 	/usr/local/go/src/io/io.go:354 +0xb2
++ 02:13:38.300 github.com/flynn/flynn/pkg/exec.func·001()
++ 02:13:38.300 	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/exec/exec.go:232 +0x86
++ 02:13:38.300 created by github.com/flynn/flynn/pkg/exec.(*Cmd).Start
++ 02:13:38.300 	/home/ubuntu/go/src/github.com/flynn/flynn/pkg/exec/exec.go:234 +0xd09
```

So `exec.Cmd` has realised the job has failed, and tries to call `attachClient.Close`, but that blocks because `attachClient.Write` has the mutex locked.

We need to investigate why the `attachClient.Write` is blocking for so long.

**Comment by lmars** [comment]
I was unable to reproduce this with a test case, and looking more closely at the stack traces, both the `Close` and `Write` goroutines are blocked trying to lock the mutex, and it is unclear which goroutine actually holds the lock.
