### ISSUE TITLE
AWS: Can not install flynn cluster in EU region

### ISSUE THREAD

**Issue by arekkas** [flynn/flynn#1654]
Flynn installer hangs at "Event log: Creating stack" - I can't see any new stack in CloudFormation as well.

Any ideas?

**Comment by titanous** [comment]
I'm currently launching a cluster in the EU (Ireland) region with no issues. Send a SIGQUIT to the `flynn install` process to get a goroutine dump.

**Comment by arekkas** [comment]
Weird, I've been trying it multiple times without success. Here's the dump:

```
$ flynn install
Open http://localhost:50694 in your browser to continue.
INFO[07-12|20:07:49] Event: new_credential:  
INFO[07-12|20:07:56] Event: new_cluster:  
INFO[07-12|20:07:56] Event: log: Creating key pair 
INFO[07-12|20:07:56] Event: prompt:  
INFO[07-12|20:08:00] Event: prompt:  
INFO[07-12|20:08:00] Event: log: Deleting key pair 
INFO[07-12|20:08:00] Event: log: Creating key pair 
INFO[07-12|20:08:01] Event: log: Allocating domain 
INFO[07-12|20:08:02] Event: log: Fetching image manifest 
INFO[07-12|20:08:02] Event: log: Generating start script 
INFO[07-12|20:08:03] Event: log: Creating stack 
SIGQUIT: quit
PC=0x86e6b m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x107, 0x1, 0x49dac, 0x67, 0x0, 0x107ece0, 0x7a689, 0xffffffffffffffff, 0x4786d, 0x7fff5fbff6fc, ...)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/sys_darwin_amd64.s:407 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x4786d)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/os1_darwin.go:380 +0xeb
runtime.semasleep.func1()
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/os1_darwin.go:396 +0x29
runtime.systemstack(0x7fff5fbff700)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:278 +0xb1
runtime.semasleep(0xffffffffffffffff, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/os1_darwin.go:397 +0x36
runtime.notesleep(0x107f5a8)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/lock_sema.go:169 +0x10f
runtime.stopm()
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc1.go:1122 +0x124
runtime.findrunnable(0x821201500, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc1.go:1508 +0x6bf
runtime.schedule()
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc1.go:1617 +0x282
runtime.park_m(0x8212a3500)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc1.go:1676 +0x1ac
runtime.mcall(0x7fff5fbff880)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:204 +0x5e

goroutine 1 [IO wait, 4 minutes]:
net.runtime_pollWait(0x88213d20b0, 0x72, 0x8211f0180)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x821564920, 0x72, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0x821564920, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0x8215648c0, 0x0, 0x88213d21c0, 0x8215e8a60)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0x82155e1d0, 0x8215bb890, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/tcpsock_posix.go:249 +0x4d
net.(*TCPListener).Accept(0x82155e1d0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/tcpsock_posix.go:259 +0x3d
net/http.(*Server).Serve(0x821338f00, 0x88213d1108, 0x82155e1d0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1820 +0xb3
net/http.Serve(0x88213d1108, 0x82155e1d0, 0x88213d2198, 0x8213234e0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1698 +0x85
github.com/flynn/flynn/installer.ServeHTTP(0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/http.go:102 +0xbf1
main.runInstaller(0x8213d8280, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/cli/install.go:21 +0x24
main.runCommand(0x7fff5fbffa3e, 0x7, 0x10aaa08, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/cli/main.go:182 +0xc00
main.main()
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/cli/main.go:119 +0xd31

goroutine 5 [syscall, 30 minutes]:
os/signal.loop()
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive, 30 minutes]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0x8211eef60)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:54 +0x16a
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xc3

goroutine 17 [select, 30 minutes, locked to thread]:
runtime.gopark(0xac5220, 0x821208728, 0x93e450, 0x6, 0x57f18, 0x2)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:185 +0x169
runtime.selectgoImpl(0x821208728, 0x0, 0x18)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0x821208728)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/signal1_unix.go:190 +0x326
runtime.goexit()
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 21 [chan receive, 30 minutes]:
database/sql.(*DB).connectionOpener(0x82135d680)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/database/sql/sql.go:481 +0x336

goroutine 14 [IO wait, 30 minutes]:
net.runtime_pollWait(0x88213d1ff0, 0x72, 0x8211f0180)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0x821564990, 0x72, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0x821564990, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0x821564930, 0x821414000, 0x8000, 0x8000, 0x0, 0x8821391050, 0x8211f0180)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0x82155e1e8, 0x821414000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/net.go:124 +0xe4
io.copyBuffer(0x8821396440, 0x821548058, 0x88213d2270, 0x82155e1e8, 0x821414000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/io/io.go:381 +0x247
io.Copy(0x8821396440, 0x821548058, 0x88213d2270, 0x82155e1e8, 0x82135d660, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/io/io.go:351 +0x64
net/http.(*conn).closeNotify.func1(0x821548058, 0x88213d2270, 0x82155e1e8, 0x821568210)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:182 +0x64
created by net/http.(*conn).closeNotify
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:188 +0x361

goroutine 34 [chan receive, 30 minutes]:
github.com/flynn/flynn/pkg/sse.ServeStream(0x88213d2368, 0x821500370, 0x6cfd00, 0x821338120, 0x8821411220, 0x8213d82a0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/pkg/sse/stream.go:46 +0x2b3
github.com/flynn/flynn/installer.(*httpAPI).Events(0x8214ae500, 0x88213d2368, 0x821500370, 0x821344540, 0x0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/http.go:231 +0x12a
github.com/flynn/flynn/installer.(*httpAPI).Events-fm(0x88213d2368, 0x821500370, 0x821344540, 0x0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/http.go:87 +0x5c
github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x821323060, 0x88213d2368, 0x821500370, 0x821344540)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter/router.go:276 +0x18d
github.com/flynn/flynn/installer.(*httpAPI).CorsHandler.func1(0x88213d2368, 0x821500370, 0x821344540)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/http.go:116 +0x83
net/http.HandlerFunc.ServeHTTP(0x8213234e0, 0x88213d2368, 0x821500370, 0x821344540)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1355 +0x3a
net/http.serverHandler.ServeHTTP(0x821338f00, 0x88213d2368, 0x821500370, 0x821344540)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1795 +0x19e
net/http.(*conn).serve(0x821568210)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1294 +0xbea
created by net/http.(*Server).Serve
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1843 +0x3f6

goroutine 12 [chan receive, 30 minutes]:
github.com/flynn/flynn/pkg/sse.(*Stream).Serve.func1(0x88213963c0, 0x821500370, 0x8213daaf0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/pkg/sse/stream.go:58 +0x4e
created by github.com/flynn/flynn/pkg/sse.(*Stream).Serve
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/pkg/sse/stream.go:60 +0x2be

goroutine 13 [select]:
reflect.rselect(0x82145cea0, 0x3, 0x3, 0x821338120, 0x3)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/select.go:650 +0x11f
reflect.Select(0x8214c1eb8, 0x3, 0x3, 0x82145ce40, 0x0, 0x0, 0x0, 0x1)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/reflect/value.go:1998 +0x282
github.com/flynn/flynn/pkg/sse.(*Stream).Serve.func2(0x8213daaf0, 0x6d05a0, 0x821338180, 0x12, 0x6cfd00, 0x821338120, 0x12)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/pkg/sse/stream.go:81 +0x1b1
created by github.com/flynn/flynn/pkg/sse.(*Stream).Serve
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/pkg/sse/stream.go:97 +0x3bd

goroutine 73 [sleep]:
time.Sleep(0x3b9aca00)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/time.go:59 +0xf9
github.com/flynn/flynn/installer.(*AWSCluster).waitForStackCompletion(0x82123e0d0, 0x9383f8, 0x6, 0xecd34a403, 0x8058f553f, 0x107e7c0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/aws_cluster.go:561 +0x30e
github.com/flynn/flynn/installer.(*AWSCluster).createStack(0x82123e0d0, 0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/aws_cluster.go:454 +0x113f
github.com/flynn/flynn/installer.(*AWSCluster).(github.com/flynn/flynn/installer.createStack)-fm(0x0, 0x0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/aws_cluster.go:153 +0x2e
github.com/flynn/flynn/installer.(*AWSCluster).Run.func1(0x82123e0d0)
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/aws_cluster.go:161 +0x371
created by github.com/flynn/flynn/installer.(*AWSCluster).Run
	/tmp/tmp.tcW7bwnMVZ/src/github.com/flynn/flynn/installer/aws_cluster.go:175 +0x35

rax    0xe
rbx    0x107
rcx    0x7fff5fbff688
rdx    0x7fff5fbff700
rdi    0x107
rsi    0x0
rbp    0x107f4a0
rsp    0x7fff5fbff688
r8     0x7fff5fbff640
r9     0x7fff5fbff2d4
r10    0x0
r11    0x286
r12    0x0
r13    0x456406da4d0
r14    0x13f046f00fa8bc00
r15    0x0
rip    0x86e6b
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
```

**Comment by titanous** [comment]
@jvatic will handle debugging this, it looks like it is waiting for the stack to start on AWS.

**Comment by arekkas** [comment]
If it helps anything: I updated the flynn cli today

**Comment by jvatic** [comment]
@arekkas I'm unable to reproduce this issue, are you using the default instance type / number of instances? Also, is it possible you've reached some sort of limit in AWS?

**Comment by arekkas** [comment]
```
$ flynn version
v20150710.0
```

All settings are the default settings, except for the region. I also removed `~/.flynn`, without success.

**Comment by arekkas** [comment]
Ok, so I removed `~/.flynn` again, manually cleaned up the AWS account (some stacks had `DELETE_FAILED` statuses) and now it seems to be working again. Thanks for the help!

ps: I do not believe that I've hit any sort of limit.
