### ISSUE TITLE
Second rails push with ruby-2.2.2 fails

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1757]
With an empty Rails app and `ruby "2.2.2"` specified in the `Gemfile`, the second push fails with this error:

```text
-----> Building cranes-cuddle-belleville...
-----> Ruby app detected
remote: cp: failed to access 'vendor/heroku': Permission denied
-----> Compiling Ruby/Rails
remote: /usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir': Permission denied - vendor/ruby-2.2.2 (Errno::EACCES)
remote: 	from /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
remote: 	from /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
remote: 	from /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
remote: 	from /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
remote: 	from /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
remote: 	from /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/ruby.rb:318:in `block in install_ruby'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/ruby.rb:305:in `install_ruby'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/ruby.rb:85:in `block in compile'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/ruby.rb:80:in `compile'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/rails2.rb:49:in `block in compile'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/rails2.rb:47:in `compile'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/rails3.rb:38:in `block in compile'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/rails3.rb:37:in `compile'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/rails4.rb:41:in `block in compile'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:48:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:44:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/rails4.rb:40:in `compile'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/bin/compile:16:in `block (2 levels) in <main>'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/base.rb:125:in `log'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/bin/compile:15:in `block in <main>'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `call'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `block in trace'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote: 	from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `trace'
remote: 	from /tmp/buildpacks/000003_heroku-buildpack-ruby/bin/compile:11:in `<main>'
       !
       !     Permission denied - vendor/ruby-2.2.2
       !
remote: Build failed: exec: job exited with status 1
To ssh://git@dev.localflynn.com:2222/cranes-cuddle-belleville.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@dev.localflynn.com:2222/cranes-cuddle-belleville.git'
```

Reported by @josephglanville on IRC.

**Comment by titanous** [comment]
This appears to have been caused by #1617, but I haven't sorted out why yet.
