### ISSUE TITLE
Some kind of go error/panic when doing cluster add

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#1924]
```
$ flynn cluster add -p <Base64 string> default cluster.bemt.eu <key/hash> -f
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc2080d0810, 0x0, 0x0, 0x0, 0x7e30e0, 0xc208032010)
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x12e
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x73
github.com/flynn/flynn/cli/config.(*Config).Add(0xc2080d1d10, 0xc208055300, 0x8d5301, 0x0, 0x0)
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/cli/config/config.go:118 +0x630
main.runClusterAdd(0xc2080ec580, 0x0, 0x0)
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/cli/cluster.go:95 +0x5d4
main.runCluster(0xc2080ec580, 0x0, 0x0)
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/cli/cluster.go:51 +0x109
main.runCommand(0x7fff5fbffbce, 0x7, 0xc208054e80, 0x7, 0x8, 0x0, 0x0)
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/cli/main.go:176 +0x8ba
main.main()
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/cli/main.go:122 +0xd1a

goroutine 5 [syscall]:
os/signal.loop()
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 11 [runnable]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc2080d0810)
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/pkg/shutdown/handler.go:55
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.NETonRerUm/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8
```
```
$ flynn --version
v20151001.0
```
I have a "default" cluster already but I want to overwrite that config. If I change "default" to another name (that also exists in ~/.flynnrc) the command executes as properly.

**Comment by titanous** [comment]
Reproduced, patch coming soon.
