### ISSUE TITLE
Segfault on 'flynn-host download'

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2211]
```
===> 20:04:26.886 running "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin"
t=2015-11-30T20:04:26+0000 lvl=info msg="initializing TUF client"
unexpected fault address 0x7efbfc81f029
fatal error: fault
[signal 0xb code=0x1 addr=0x7efbfc81f029 pc=0x4701c7]

goroutine 1 [running]:
runtime.gothrow(0xb570f0, 0x5)
        /usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc2080e1120 sp=0xc2080e1108
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080e1170 sp=0xc2080e1120
runtime.memmove(0xc20827c000, 0x7efbfc81f029, 0x5ce)
        /usr/local/go/src/runtime/memmove_amd64.s:216 +0x97 fp=0xc2080e1178 sp=0xc2080e1170
bytes.(*Reader).Read(0xc208285500, 0xc20827c000, 0x2000, 0x2000, 0x4f8217, 0x0, 0x0)
        /usr/local/go/src/bytes/reader.go:40 +0x12d fp=0xc2080e11d0 sp=0xc2080e1178
io.(*teeReader).Read(0xc2082a6720, 0xc20827c000, 0x2000, 0x2000, 0x7efbfc7e2340, 0x0, 0x0)
        /usr/local/go/src/io/io.go:495 +0x83 fp=0xc2080e1248 sp=0xc2080e11d0
io/ioutil.devNull.ReadFrom(0x0, 0x7efbfc7e4c70, 0xc2082a6720, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:151 +0xb1 fp=0xc2080e12a0 sp=0xc2080e1248
io/ioutil.(*devNull).ReadFrom(0xc20802a300, 0x7efbfc7e4c70, 0xc2082a6720, 0x7efbfc7e49b0, 0x0, 0x0)
        <autogenerated>:9 +0xbb fp=0xc2080e12d8 sp=0xc2080e12a0
io.Copy(0x7efbfc7dde88, 0xc20802a300, 0x7efbfc7e4c70, 0xc2082a6720, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:358 +0x13d fp=0xc2080e1390 sp=0xc2080e12d8
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/util.GenerateFileMeta(0x7efbfc7e4c70, 0xc2082a6720, 0xc2082935f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/util/util.go:96 +0x402 fp=0xc2080e15c8 sp=0xc2080e1390
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).hasMeta(0xc208046420, 0xb8ba90, 0x9, 0x5ce, 0xc2082854a0, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:515 +0x202 fp=0xc2080e16d0 sp=0xc2080e15c8
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).update(0xc208046420, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:200 +0x8b8 fp=0xc2080e18d8 sp=0xc2080e16d0
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).Update(0xc208046420, 0x1, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:128 +0x3f fp=0xc2080e1908 sp=0xc2080e18d8
github.com/flynn/flynn/host/cli.updateTUFClient(0xc208046420, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/cli/download.go:115 +0x3d fp=0xc2080e1978 sp=0xc2080e1908
github.com/flynn/flynn/host/cli.updateTUFClient(0xc208046420, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/cli/download.go:123 +0x158 fp=0xc2080e19e8 sp=0xc2080e1978
github.com/flynn/flynn/host/cli.runDownload(0xc2080d5ae0, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/cli/download.go:59 +0x800 fp=0xc2080e1c20 sp=0xc2080e19e8
github.com/flynn/flynn/host/cli.Run(0x7fff3bb09cc4, 0x8, 0xc20806e900, 0x8, 0x8, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x677 fp=0xc2080e1d48 sp=0xc2080e1c20
main.main()
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/host.go:127 +0x8c1 fp=0xc2080e1f98 sp=0xc2080e1d48
runtime.main()
        /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080e1fe0 sp=0xc2080e1f98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080e1fe8 sp=0xc2080e1fe0

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc208032d20)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc2080800b0)
        /usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc2080800b0)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc
===> 20:04:27.675 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 2
```

I will keep the cluster around for a bit, if you need more info.

**Comment by temujin9** [comment]
This is repeatable:
```
===> 20:22:13.886 running "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin"
t=2015-11-30T20:22:13+0000 lvl=info msg="initializing TUF client"
unexpected fault address 0x7f27c663f029
fatal error: fault
[signal 0xb code=0x1 addr=0x7f27c663f029 pc=0x4701c7]

goroutine 1 [running]:
runtime.gothrow(0xb570f0, 0x5)
        /usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc2080e1120 sp=0xc2080e1108
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080e1170 sp=0xc2080e1120
runtime.memmove(0xc20827c000, 0x7f27c663f029, 0x5ce)
        /usr/local/go/src/runtime/memmove_amd64.s:216 +0x97 fp=0xc2080e1178 sp=0xc2080e1170
bytes.(*Reader).Read(0xc208285500, 0xc20827c000, 0x2000, 0x2000, 0x4f8217, 0x0, 0x0)
        /usr/local/go/src/bytes/reader.go:40 +0x12d fp=0xc2080e11d0 sp=0xc2080e1178
io.(*teeReader).Read(0xc2082a6720, 0xc20827c000, 0x2000, 0x2000, 0x7f27c6602270, 0x0, 0x0)
        /usr/local/go/src/io/io.go:495 +0x83 fp=0xc2080e1248 sp=0xc2080e11d0
io/ioutil.devNull.ReadFrom(0x0, 0x7f27c6604c90, 0xc2082a6720, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:151 +0xb1 fp=0xc2080e12a0 sp=0xc2080e1248
io/ioutil.(*devNull).ReadFrom(0xc20802a300, 0x7f27c6604c90, 0xc2082a6720, 0x7f27c66048e0, 0x0, 0x0)
        <autogenerated>:9 +0xbb fp=0xc2080e12d8 sp=0xc2080e12a0
io.Copy(0x7f27c65fddc8, 0xc20802a300, 0x7f27c6604c90, 0xc2082a6720, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:358 +0x13d fp=0xc2080e1390 sp=0xc2080e12d8
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/util.GenerateFileMeta(0x7f27c6604c90, 0xc2082a6720, 0xc208293600, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/util/util.go:96 +0x402 fp=0xc2080e15c8 sp=0xc2080e1390
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).hasMeta(0xc208046420, 0xb8ba90, 0x9, 0x5ce, 0xc2082854a0, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:515 +0x202 fp=0xc2080e16d0 sp=0xc2080e15c8
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).update(0xc208046420, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:200 +0x8b8 fp=0xc2080e18d8 sp=0xc2080e16d0
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).Update(0xc208046420, 0x1, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:128 +0x3f fp=0xc2080e1908 sp=0xc2080e18d8
github.com/flynn/flynn/host/cli.updateTUFClient(0xc208046420, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/cli/download.go:115 +0x3d fp=0xc2080e1978 sp=0xc2080e1908
github.com/flynn/flynn/host/cli.updateTUFClient(0xc208046420, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/cli/download.go:123 +0x158 fp=0xc2080e19e8 sp=0xc2080e1978
github.com/flynn/flynn/host/cli.runDownload(0xc2080d7ae0, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/cli/download.go:59 +0x800 fp=0xc2080e1c20 sp=0xc2080e19e8
github.com/flynn/flynn/host/cli.Run(0x7ffd4094ccc4, 0x8, 0xc20806e900, 0x8, 0x8, 0x0, 0x0)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x677 fp=0xc2080e1d48 sp=0xc2080e1c20
main.main()
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/host/host.go:127 +0x8c1 fp=0xc2080e1f98 sp=0xc2080e1d48
runtime.main()
        /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080e1fe0 sp=0xc2080e1f98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080e1fe8 sp=0xc2080e1fe0

goroutine 6 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc208084d20)
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
        /tmp/tmp.vE4Lstw3ZB/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc20807e160)
        /usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc20807e160)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc
===> 20:22:14.021 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 2
```

**Comment by titanous** [comment]
I'm looking into this.

**Comment by titanous** [comment]
I assume this is on EC2?

**Comment by titanous** [comment]
I haven't been able to replicate this yet. Can you get a core dump? What EC2 instance type?

**Comment by titanous** [comment]
FYI I have successfully reproduced this and retrieved a core dump.

**Comment by titanous** [comment]
As far as I can tell this is a bug in the buffer pool system that `ioutil.Discard.ReadFrom` uses. I'm going to see if I can update to Go 1.5 easily, and if not will do a workaround that avoids that code path.

**Comment by titanous** [comment]
New backtrace with the workaround applied:

```text
    amazon-ebs: t=2015-12-01T17:26:13+0000 lvl=info msg="initializing TUF client"
    amazon-ebs: unexpected fault address 0x7efe5c6dd029
    amazon-ebs: fatal error: fault
    amazon-ebs: [signal 0xb code=0x1 addr=0x7efe5c6dd029 pc=0x4701c7]
    amazon-ebs:
    amazon-ebs: goroutine 1 [running]:
    amazon-ebs: runtime.gothrow(0xb57610
    amazon-ebs: /usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc2080e11b0 sp=0xc2080e1198
    amazon-ebs: runtime.sigpanic()
    amazon-ebs: /usr/local/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080e1200 sp=0xc2080e11b0
    amazon-ebs: runtime.memmove(0xc208284000
    amazon-ebs: /usr/local/go/src/runtime/memmove_amd64.s:216 +0x97 fp=0xc2080e1208 sp=0xc2080e1200
    amazon-ebs: bytes.(*Reader).Read(0xc20828c210
    amazon-ebs: /usr/local/go/src/bytes/reader.go:40 +0x12d fp=0xc2080e1260 sp=0xc2080e1208
    amazon-ebs: io.(*teeReader).Read(0xc20829c420
    amazon-ebs: /usr/local/go/src/io/io.go:495 +0x83 fp=0xc2080e12d8 sp=0xc2080e1260
    amazon-ebs: io.Copy(0x7efe5c69d7c0
    amazon-ebs: /usr/local/go/src/io/io.go:362 +0x1f6 fp=0xc2080e1390 sp=0xc2080e12d8
    amazon-ebs: github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/util.GenerateFileMeta(0x7efe5c6a3c60
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/util/util.go:96 +0x402 fp=0xc2080e15c8 sp=0xc2080e1390
    amazon-ebs: github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).hasMeta(0xc208032420
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:515 +0x202 fp=0xc2080e16d0 sp=0xc2080e15c8
    amazon-ebs: github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).update(0xc208032420
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:200 +0x8b8 fp=0xc2080e18d8 sp=0xc2080e16d0
    amazon-ebs: github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).Update(0xc208032420
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:128 +0x3f fp=0xc2080e1908 sp=0xc2080e18d8
    amazon-ebs: github.com/flynn/flynn/host/cli.updateTUFClient(0xc208032420
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/host/cli/download.go:133 +0x3d fp=0xc2080e1978 sp=0xc2080e1908
    amazon-ebs: github.com/flynn/flynn/host/cli.updateTUFClient(0xc208032420
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/host/cli/download.go:141 +0x158 fp=0xc2080e19e8 sp=0xc2080e1978
    amazon-ebs: github.com/flynn/flynn/host/cli.runDownload(0xc2080d5ae0
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/host/cli/download.go:77 +0x800 fp=0xc2080e1c20 sp=0xc2080e19e8
    amazon-ebs: github.com/flynn/flynn/host/cli.Run(0x7ffd245e4cf6
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x677 fp=0xc2080e1d48 sp=0xc2080e1c20
    amazon-ebs: main.main()
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/host/host.go:127 +0x8c1 fp=0xc2080e1f98 sp=0xc2080e1d48
    amazon-ebs: runtime.main()
    amazon-ebs: /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080e1fe0 sp=0xc2080e1f98
    amazon-ebs: runtime.goexit()
    amazon-ebs: /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080e1fe8 sp=0xc2080e1fe0
    amazon-ebs:
    amazon-ebs: goroutine 6 [syscall]:
    amazon-ebs: os/signal.loop()
    amazon-ebs: /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
    amazon-ebs: created by os/signal.init·1
    amazon-ebs: /usr/local/go/src/os/signal/signal_unix.go:27 +0x35
    amazon-ebs:
    amazon-ebs: goroutine 17 [syscall
    amazon-ebs: runtime.goexit()
    amazon-ebs: /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
    amazon-ebs:
    amazon-ebs: goroutine 7 [chan receive]:
    amazon-ebs: github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc208080d20)
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x158
    amazon-ebs: created by github.com/flynn/flynn/pkg/shutdown.newHandler
    amazon-ebs: /tmp/tmp.crCxnrnziG/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8
```

New theory is that it is a race.

**Comment by titanous** [comment]
Found the issue: flynn/go-tuf#90
