### ISSUE TITLE
controller: Shutdown blocks closing DB pool

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2327]
The controller currently does not terminate on SIGTERM as it gets blocked trying to close the DB connection pool, likely because we have listeners which are not explicitly closed on shutdown (so are blocking the pool from closing).

This means that every time we try and stop a web job, it takes 10s before it actually stops (due to the 10s SIGKILL timeout), so deploying the controller with 2 web process is spending 20s each time waiting. Given we deploy the controller 6 or 7 times in CI, this is adding 2-3 minutes to CI builds.

/cc @josephglanville

**Comment by lmars** [comment]
FYI some blocked goroutines after the controller receives `SIGTERM`:

```
goroutine 6 [semacquire]:
sync.(*Cond).Wait(0xc208033300)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/sync/cond.go:62 +0x9e
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*ConnPool).Close(0xc208046400)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn_pool.go:171 +0xd0
main.func·003()
        /home/ubuntu/go/src/github.com/flynn/flynn/controller/controller.go:71 +0x2d
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc20803ac00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/shutdown/handler.go:66 +0xf7
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc20803ac00)
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/shutdown/handler.go:59 +0x19a
created by github.com/flynn/flynn/pkg/shutdown.newHandler
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 102 [IO wait]:
net.(*pollDesc).Wait(0xc208147410, 0x72, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208147410, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081473b0, 0xc2081a3000, 0x1000, 0x1000, 0x0, 0x7f7342108df0, 0xc20811c600)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208036ee0, 0xc2081a3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc208171140)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208171140, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:132 +0xf0
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Conn).waitForNotification(0xc2080b5200, 0xece067e1e, 0x819cb29, 0xa74c20, 0xece067e1e, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn.go:754 +0x102
github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx.(*Conn).WaitForNotification(0xc2080b5200, 0x2540be400, 0x7f7342104b80, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/jackc/pgx/conn.go:729 +0x593
github.com/flynn/flynn/pkg/postgres.(*Listener).listen(0xc2081bf620)
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/postgres/listener.go:53 +0x3b
created by github.com/flynn/flynn/pkg/postgres.(*DB).Listen
        /home/ubuntu/go/src/github.com/flynn/flynn/pkg/postgres/listener.go:28 +0x235
```

**Comment by josephglanville** [comment]
I'll look into this.
