### ISSUE TITLE
flynn-host update blows up

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#2446]
```
root@flynn-node:~# flynn-host update
INFO[02-12|06:21:15] initializing TUF client
INFO[02-12|06:21:15] updating TUF data
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7f7aa8]

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc208092ab0, 0x0, 0x0, 0x0, 0xa83660, 0xc20802a050)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x12e
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x73
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed.VerifySignatures(0xc2088faea0, 0xb60d10, 0x4, 0x0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed/verify.go:62 +0xa8
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed.Verify(0xc2088faea0, 0xb60d10, 0x4, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed/verify.go:32 +0x72
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed.Unmarshal(0xc2088b7200, 0x5ce, 0x600, 0x9354e0, 0xc2088f5540, 0xb60d10, 0x4, 0x0, 0x0, 0x0, ...)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed/verify.go:112 +0x117
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).decodeRoot(0xc2080bc240, 0xc2088b7200, 0x5ce, 0x600, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:458 +0xde
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).updateWithLatestRoot(0xc2080bc240, 0x0, 0xc20808d360, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:240 +0x14d
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).update(0xc2080bc240, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:136 +0xcd
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).Update(0xc2080bc240, 0xbd2fd0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:128 +0x3f
github.com/flynn/flynn/host/cli.updateAndExecLatest(0xc20804ebe9, 0xa, 0xc2080bc240, 0x7f1471a43430, 0xc20808c0a0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/cli/update.go:238 +0x9a
github.com/flynn/flynn/host/cli.runUpdate(0xc20808c080, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/cli/update.go:62 +0x7eb
github.com/flynn/flynn/host/cli.Run(0x7fff1c0c593b, 0x6, 0x10e4070, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x677
main.main()
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/host.go:128 +0x8c1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc208092ab0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc208070580)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc208070580)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

root@flynn-node:~# flynn-host version
v20151223.0
```

**Comment by josephglanville** [comment]
I think this is a bi-product of an expiry of one of our manifests, which has now been fixed but required updating all of the signing certs etc.

Now, I believe the right solution is to delete the TUF database, which I don't think has any adverse effects.

However I am not the expert on the TUF situation so you may want to wait for @lmars or @titanous to chime in on what should be done here.

**Comment by titanous** [comment]
Deleting `/etc/flynn/tuf.db` should fix this.

**Comment by lmars** [comment]
You will also need to run `flynn-host download` after deleting `/etc/flynn/tuf.db` to download the latest, fixed `flynn-host` binary before running `flynn-host update`.
