### ISSUE TITLE
flynn-host fd exhaustion caused by failed stop

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2461]
I just ran into a cluster where `flynn-host` ran out of fds for the following reasons:
1. The scheduler wanted to terminate a job running on the host and sent a `DELETE` request to the `flynn-host` daemon and there were no available connection to reuse so it established a new TCP connection for the HTTP request to flynn-host.
2. `flynn-host` sent a `Stop` RPC to the `containerinit` process.
3. For some reason `containerinit` never responded to the RPC, so a HTTP response was never returned to the scheduler.
4. GOTO 1

This loop resulted in fd exhaustion in the `flynn-host` daemon. We should have safeguards that prevent this scenario.

**Comment by titanous** [comment]
Here's an example stuck RPC goroutine:

```text
goroutine 264225 [chan receive, 5009 minutes]:
github.com/flynn/flynn/pkg/rpcplus.(*Client).Call(0xc2082eb0e0, 0xbab210, 0x14, 0x96e2e0, 0xc2096cc4a8, 0x94df20, 0x10ef0a0, 0x0, 0x0)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/pkg/rpcplus/client.go:412 +0xd6
github.com/flynn/flynn/host/containerinit.(*Client).Signal(0xc208035538, 0xf, 0x0, 0x0)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/host/containerinit/init.go:156 +0xe3
main.(*libvirtContainer).Stop(0xc208372050, 0x0, 0x0)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:940 +0x47
main.(*LibvirtLXCBackend).Stop(0xc208064a00, 0xc209653e12, 0x31, 0x0, 0x0)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:954 +0x85
main.(*Host).StopJob(0xc208057e00, 0xc209653e12, 0x31, 0x0, 0x0)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/host/http.go:78 +0x6ff
main.(*jobAPI).StopJob(0xc2080342b8, 0x7f314658b638, 0xc209484990, 0xc209c53e10, 0xc209403220, 0x1, 0x1)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/host/http.go:146 +0x87
main.*jobAPI.StopJob·fm(0x7f314658b638, 0xc209484990, 0xc209c53e10, 0xc209403220, 0x1, 0x1)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/host/http.go:486 +0x63
github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc2080c9520, 0x7f314658b638, 0xc209484990, 0xc209c53e10)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter/router.go:276 +0x188
github.com/flynn/flynn/pkg/httphelper.func·004(0x7f314658b638, 0xc209484990, 0xc209c53e10)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/pkg/httphelper/request_logger.go:34 +0x8a0
net/http.HandlerFunc.ServeHTTP(0xc2080bd5d0, 0x7f314658b638, 0xc209484990, 0xc209c53e10)
	/usr/local/go/src/net/http/server.go:1265 +0x41
github.com/flynn/flynn/pkg/httphelper.func·003(0x7f314658b558, 0xc209f0b040, 0xc209c53e10)
	/tmp/tmp.Z0ELp3CIwu/src/github.com/flynn/flynn/pkg/httphelper/httphelper.go:123 +0x25c
net/http.HandlerFunc.ServeHTTP(0xc2080c95e0, 0x7f314658b558, 0xc209f0b040, 0xc209c53e10)
	/usr/local/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0xc20802faa0, 0x7f314658b558, 0xc209f0b040, 0xc209c53e10)
	/usr/local/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2095bb680)
	/usr/local/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
