### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2487]
Hi,

I just tried to run a

``` bash
sudo flynn-host update
```

On my first node and it died:

> INFO[02-23|00:42:57] binaries and config pulled successfully  host=flynn0
> INFO[02-23|00:42:57] binaries and config pulled successfully  host=flynn2
> INFO[02-23|00:42:58] binaries and config pulled successfully  host=flynn1
> INFO[02-23|00:42:58] validating binaries
> INFO[02-23|00:42:58] updating flynn-host daemon on all hosts
> INFO[02-23|00:43:02] flynn-host updated successfully          host=flynn2
> INFO[02-23|00:43:03] flynn-host updated successfully          host=flynn0
> INFO[02-23|00:43:19] flynn-host updated successfully          host=flynn1
> EROR[02-22|23:43:49] cluster status is unhealthy              code=500

The cluster was freshly setup with the same version the updater tried to install. I just wanted to check if there is a new version available.
What I did with the cluster so far:
- Setup it a few days ago
- Deployed a PHP application
- Setup some monitoring Pinging the PHP application every 5 minutes and the Status application as well
- Left it alone until today

**Comment by lmars** [comment]
@philiplb is the Flynn CLI still functional? If so, can you gist the output of the following:

```
$ flynn run curl http://status-web.discoverd
```

**Comment by philiplb** [comment]
Hi,
thanks @lmars. Yes, this worked, but took about 1-2 minutes:

```json
{
  "data": {
    "status": "unhealthy",
    "detail": {
      "blobstore": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller-scheduler": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller-worker": {
        "status": "unhealthy"
      },
      "dashboard": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "discoverd": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "flannel": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "gitreceive": {
        "status": "unhealthy"
      },
      "logaggregator": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "postgres": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "router": {
        "status": "healthy",
        "version": "v20160218.0"
      }
    },
    "version": "v20160218.0"
  }
}
```

**Comment by jontonsoup** [comment]
+1 getting this error as well. 

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7f7aa8]

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc208086db0, 0x0, 0x0, 0x0, 0xa83660, 0xc20802a050)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x12e
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x73
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed.VerifySignatures(0xc208912ea0, 0xb60d10, 0x4, 0x0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed/verify.go:62 +0xa8
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed.Verify(0xc208912ea0, 0xb60d10, 0x4, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed/verify.go:32 +0x72
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed.Unmarshal(0xc20890b200, 0x5ce, 0x600, 0x9354e0, 0xc20890d5e0, 0xb60d10, 0x4, 0x0, 0x0, 0x0, ...)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/signed/verify.go:112 +0x117
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).decodeRoot(0xc2080f02a0, 0xc20890b200, 0x5ce, 0x600, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:458 +0xde
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).updateWithLatestRoot(0xc2080f02a0, 0x0, 0xc2080ca640, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:240 +0x14d
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).update(0xc2080f02a0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:136 +0xcd
github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client.(*Client).Update(0xc2080f02a0, 0xbd2fd0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/flynn/go-tuf/client/client.go:128 +0x3f
github.com/flynn/flynn/host/cli.updateAndExecLatest(0xc2080506a9, 0xa, 0xc2080f02a0, 0x7f1f3615a500, 0xc20800bb00, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/cli/update.go:238 +0x9a
github.com/flynn/flynn/host/cli.runUpdate(0xc20800bae0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/cli/update.go:62 +0x7eb
github.com/flynn/flynn/host/cli.Run(0x7ffc5b4eb984, 0x6, 0x10e4070, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x677
main.main()
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/host.go:128 +0x8c1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc208086db0)
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc20807e630)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc20807e630)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by titanous** [comment]
@jontonsoup I believe that's a separate issue, please try the instructions in this post: https://flynn.io/blog/2016-02-15-this-week-in-flynn

**Comment by philiplb** [comment]
Today, I tried again and got the same error. Then I ran
```bash
sudo flynn-host fix --min-hosts 3
```
with the output

> INFO[02-24|11:04:25] found expected hosts                     n=3
> INFO[02-24|11:04:25] ensuring discoverd is running on all hosts
> INFO[02-24|11:04:25] checking flannel
> INFO[02-24|11:04:25] flannel looks good
> INFO[02-24|11:04:25] waiting for discoverd to be available
> INFO[02-24|11:04:25] checking for running controller API
> INFO[02-24|11:04:25] found running controller API instances   n=2
> INFO[02-24|11:04:25] found controller instance, checking critical formations
> INFO[02-24|11:04:26] checking postgres
> INFO[02-24|11:04:26] found running postgres leader
> INFO[02-24|11:04:26] found 3 running postgres instances
> INFO[02-24|11:04:26] getting postgres status
> INFO[02-24|11:04:26] postgres claims to be read-write
> INFO[02-24|11:04:26] checking for running controller API
> INFO[02-24|11:04:26] found running controller API instances   n=2
> INFO[02-24|11:04:26] found controller instance, checking critical formations
> INFO[02-24|11:04:27] scheduler looks up, moving on
> INFO[02-24|11:04:27] cluster fix complete

And afterwards a new update attempt. This time, the update worked, all good now.
So this ticket could be closed. Or left open as the root cause is still open, why the cluster went into this state.

**Comment by philiplb** [comment]
I just also ran
```bash
flynn run curl http://status-web.discoverd
```
after the successful update. Took again some time (1-2 minutes) and has this healthy output now:
```json
{
  "data": {
    "status": "healthy",
    "detail": {
      "blobstore": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller-scheduler": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "controller-worker": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "dashboard": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "discoverd": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "flannel": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "gitreceive": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "logaggregator": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "postgres": {
        "status": "healthy",
        "version": "v20160218.0"
      },
      "router": {
        "status": "healthy",
        "version": "v20160218.0"
      }
    },
    "version": "v20160218.0"
  }
}
```

**Comment by lmars** [comment]
@philiplb please run `sudo flynn-host collect-debug-info` on each node in your cluster and post the resulting gists here, then we can try to determine why your cluster was unhealthy.

**Comment by philiplb** [comment]
Here we go:

* Node0: https://gist.github.com/philiplb/4bc95050046caeba1fc8
* Node1: https://gist.github.com/philiplb/1d2c1d62d339aefe904b
* Node2: https://gist.github.com/philiplb/36875e3a99814bd97330

**Comment by onnimonni** [comment]
I tested in place updater in my staging cluster and it hangs into updating postgres application.

**What works after failing updates:**
- Read operations
- Can't set envs or push new versions or create apps

**What is broken after failing updates:**
- Write operations
- I can read anything without any errors

I also emailed you some logs to logs@flynn.io. We're not using postgres for any apps. It's just for internal flynn stuff.


I hope this helps.

```
sudo flynn-host update
INFO[11-14|15:39:45] initializing TUF client
INFO[11-14|15:39:45] updating TUF data
INFO[11-14|15:39:51] getting configured release channel
INFO[11-14|15:39:51] determining latest version of stable release channel
INFO[11-14|15:39:51] latest stable version is v20161017.1
INFO[11-14|15:39:51] downloading v20161017.1 flynn-host binary
INFO[11-14|15:39:54] executing latest flynn-host binary
INFO[11-14|15:39:54] initializing TUF client
INFO[11-14|15:39:54] reading TUF database
INFO[11-14|15:39:54] getting host list
INFO[11-14|15:39:54] updating 3 hosts
INFO[11-14|15:39:54] checking host version compatibility
INFO[11-14|15:39:54] pulling latest images on all hosts
INFO[11-14|15:39:54] pulling images                           host=grid3.flynn.stage.example.com
INFO[11-14|15:39:54] pulling images                           host=grid1.flynn.stage.example.com
INFO[11-14|15:39:54] pulling images                           host=grid2.flynn.stage.example.com
INFO[11-14|15:40:00] pulled image                             host=grid1.flynn.stage.example.com name=flynn/discoverd
INFO[11-14|15:40:07] pulled image                             host=grid3.flynn.stage.example.com name=flynn/taffy
INFO[11-14|15:40:10] pulled image                             host=grid3.flynn.stage.example.com name=flynn/logaggregator
INFO[11-14|15:40:20] pulled image                             host=grid2.flynn.stage.example.com name=flynn/postgresql
INFO[11-14|15:40:20] pulled image                             host=grid1.flynn.stage.example.com name=flynn/postgresql
INFO[11-14|15:40:24] pulled image                             host=grid2.flynn.stage.example.com name=flynn/dashboard
INFO[11-14|15:40:24] pulled image                             host=grid2.flynn.stage.example.com name=flynn/logaggregator
INFO[11-14|15:40:28] pulled image                             host=grid1.flynn.stage.example.com name=flynn/gitreceive
INFO[11-14|15:40:28] pulled image                             host=grid1.flynn.stage.example.com name=flynn/dashboard
INFO[11-14|15:40:29] pulled image                             host=grid3.flynn.stage.example.com name=flynn/redis
INFO[11-14|15:40:32] pulled image                             host=grid3.flynn.stage.example.com name=flynn/docker-receive
INFO[11-14|15:40:37] pulled image                             host=grid1.flynn.stage.example.com name=flynn/controller
INFO[11-14|15:40:40] pulled image                             host=grid1.flynn.stage.example.com name=flynn/router
INFO[11-14|15:40:45] pulled image                             host=grid2.flynn.stage.example.com name=flynn/mariadb
INFO[11-14|15:40:46] pulled image                             host=grid2.flynn.stage.example.com name=flynn/discoverd
INFO[11-14|15:40:48] pulled image                             host=grid2.flynn.stage.example.com name=flynn/gitreceive
INFO[11-14|15:40:51] pulled image                             host=grid3.flynn.stage.example.com name=flynn/mongodb
INFO[11-14|15:40:51] pulled image                             host=grid2.flynn.stage.example.com name=flynn/updater
INFO[11-14|15:40:51] pulled image                             host=grid2.flynn.stage.example.com name=flynn/docker-receive
INFO[11-14|15:40:55] pulled image                             host=grid3.flynn.stage.example.com name=flynn/flannel
INFO[11-14|15:40:55] pulled image                             host=grid2.flynn.stage.example.com name=flynn/flannel
INFO[11-14|15:40:56] pulled image                             host=grid2.flynn.stage.example.com name=flynn/controller
INFO[11-14|15:41:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/postgresql
INFO[11-14|15:41:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/controller
INFO[11-14|15:41:06] pulled image                             host=grid3.flynn.stage.example.com name=flynn/router
INFO[11-14|15:41:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/blobstore
INFO[11-14|15:41:30] pulled image                             host=grid1.flynn.stage.example.com name=flynn/slugbuilder
INFO[11-14|15:41:31] pulled image                             host=grid1.flynn.stage.example.com name=flynn/slugrunner
INFO[11-14|15:41:31] pulled image                             host=grid1.flynn.stage.example.com name=flynn/updater
INFO[11-14|15:41:31] pulled image                             host=grid1.flynn.stage.example.com name=flynn/logaggregator
INFO[11-14|15:41:32] pulled image                             host=grid1.flynn.stage.example.com name=flynn/docker-receive
INFO[11-14|15:41:33] pulled image                             host=grid1.flynn.stage.example.com name=flynn/blobstore
INFO[11-14|15:41:37] pulled image                             host=grid2.flynn.stage.example.com name=flynn/slugrunner
INFO[11-14|15:41:37] pulled image                             host=grid2.flynn.stage.example.com name=flynn/taffy
INFO[11-14|15:41:37] pulled image                             host=grid3.flynn.stage.example.com name=flynn/slugbuilder
INFO[11-14|15:41:38] pulled image                             host=grid3.flynn.stage.example.com name=flynn/blobstore
INFO[11-14|15:41:39] pulled image                             host=grid3.flynn.stage.example.com name=flynn/gitreceive
INFO[11-14|15:41:39] pulled image                             host=grid3.flynn.stage.example.com name=flynn/slugrunner
INFO[11-14|15:41:41] pulled image                             host=grid1.flynn.stage.example.com name=flynn/mariadb
INFO[11-14|15:41:42] pulled image                             host=grid3.flynn.stage.example.com name=flynn/status
INFO[11-14|15:41:42] pulled image                             host=grid3.flynn.stage.example.com name=flynn/discoverd
INFO[11-14|15:41:42] pulled image                             host=grid2.flynn.stage.example.com name=flynn/redis
INFO[11-14|15:41:43] pulled image                             host=grid3.flynn.stage.example.com name=flynn/dashboard
INFO[11-14|15:41:43] pulled image                             host=grid3.flynn.stage.example.com name=flynn/updater
INFO[11-14|15:41:47] pulled image                             host=grid1.flynn.stage.example.com name=flynn/mongodb
INFO[11-14|15:41:47] pulled image                             host=grid1.flynn.stage.example.com name=flynn/flannel
INFO[11-14|15:41:48] pulled image                             host=grid1.flynn.stage.example.com name=flynn/taffy
INFO[11-14|15:41:48] pulled image                             host=grid1.flynn.stage.example.com name=flynn/status
INFO[11-14|15:41:48] pulled image                             host=grid2.flynn.stage.example.com name=flynn/mongodb
INFO[11-14|15:41:48] pulled image                             host=grid2.flynn.stage.example.com name=flynn/router
INFO[11-14|15:41:49] pulled image                             host=grid2.flynn.stage.example.com name=flynn/slugbuilder
INFO[11-14|15:41:49] pulled image                             host=grid2.flynn.stage.example.com name=flynn/status
INFO[11-14|15:41:51] pulled image                             host=grid3.flynn.stage.example.com name=flynn/mariadb
INFO[11-14|15:41:53] pulled image                             host=grid1.flynn.stage.example.com name=flynn/redis
INFO[11-14|15:41:53] pulling latest binaries and config on all hosts
INFO[11-14|15:41:53] pulling binaries and config              host=grid2.flynn.stage.example.com
INFO[11-14|15:41:53] pulling binaries and config              host=grid1.flynn.stage.example.com
INFO[11-14|15:41:53] pulling binaries and config              host=grid3.flynn.stage.example.com
INFO[11-14|15:42:00] binaries and config pulled successfully  host=grid1.flynn.stage.example.com
INFO[11-14|15:42:00] binaries and config pulled successfully  host=grid3.flynn.stage.example.com
INFO[11-14|15:42:00] binaries and config pulled successfully  host=grid2.flynn.stage.example.com
INFO[11-14|15:42:00] validating binaries
INFO[11-14|15:42:00] updating flynn-host daemon on all hosts
INFO[11-14|15:42:03] flynn-host updated successfully          host=grid2.flynn.stage.example.com
INFO[11-14|15:42:03] flynn-host updated successfully          host=grid1.flynn.stage.example.com
INFO[11-14|15:42:04] flynn-host updated successfully          host=grid3.flynn.stage.example.com
INFO[11-14|13:42:04] validating images
INFO[11-14|13:42:04] creating new image artifacts
INFO[11-14|13:42:04] starting deploy of system app            name=discoverd
INFO[11-14|13:42:17] finished deploy of system app            name=discoverd
INFO[11-14|13:42:17] starting deploy of system app            name=blobstore
INFO[11-14|13:42:19] finished deploy of system app            name=blobstore
INFO[11-14|13:42:19] starting deploy of system app            name=taffy
INFO[11-14|13:42:19] finished deploy of system app            name=taffy
INFO[11-14|13:42:19] starting deploy of system app            name=dashboard
INFO[11-14|13:42:20] finished deploy of system app            name=dashboard
INFO[11-14|13:42:20] starting deploy of system app            name=router
INFO[11-14|13:42:23] finished deploy of system app            name=router
INFO[11-14|13:42:23] starting deploy of system app            name=gitreceive
INFO[11-14|13:42:24] finished deploy of system app            name=gitreceive
INFO[11-14|13:42:24] starting deploy of system app            name=docker-receive
INFO[11-14|13:42:24] finished deploy of system app            name=docker-receive
INFO[11-14|13:42:24] starting deploy of system app            name=controller
INFO[11-14|13:45:44] finished deploy of system app            name=controller
INFO[11-14|13:45:44] starting deploy of system app            name=logaggregator
INFO[11-14|13:45:45] finished deploy of system app            name=logaggregator
INFO[11-14|13:45:45] starting deploy of system app            name=postgres
EROR[11-14|13:48:46] error deploying app                      name=postgres err="timeout waiting for expected status"
15:48:46.298030 host.go:157: exec: job exited with status 1
sudo flynn-host update
INFO[11-14|15:49:01] initializing TUF client
INFO[11-14|15:49:01] updating TUF data
INFO[11-14|15:49:02] getting configured release channel
INFO[11-14|15:49:02] determining latest version of stable release channel
INFO[11-14|15:49:02] latest stable version is v20161017.1
INFO[11-14|15:49:02] downloading v20161017.1 flynn-host binary
INFO[11-14|15:49:03] executing latest flynn-host binary
INFO[11-14|15:49:03] initializing TUF client
INFO[11-14|15:49:03] reading TUF database
INFO[11-14|15:49:03] getting host list
INFO[11-14|15:49:03] updating 3 hosts
INFO[11-14|15:49:03] checking host version compatibility
INFO[11-14|15:49:03] pulling latest images on all hosts
INFO[11-14|15:49:03] pulling images                           host=grid3.flynn.stage.example.com
INFO[11-14|15:49:03] pulling images                           host=grid1.flynn.stage.example.com
INFO[11-14|15:49:03] pulling images                           host=grid2.flynn.stage.example.com
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/controller
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/gitreceive
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/slugrunner
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/dashboard
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/mariadb
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/status
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/docker-receive
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/flannel
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/router
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/redis
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/mongodb
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/slugbuilder
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/taffy
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/updater
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/logaggregator
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/discoverd
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/postgresql
INFO[11-14|15:49:04] pulled image                             host=grid1.flynn.stage.example.com name=flynn/blobstore
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/slugrunner
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/logaggregator
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/discoverd
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/postgresql
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/blobstore
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/dashboard
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/router
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/gitreceive
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/status
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/slugbuilder
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/mongodb
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/flannel
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/taffy
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/updater
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/docker-receive
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/controller
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/redis
INFO[11-14|15:49:05] pulled image                             host=grid3.flynn.stage.example.com name=flynn/mariadb
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/mongodb
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/router
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/discoverd
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/gitreceive
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/dashboard
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/redis
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/docker-receive
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/slugbuilder
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/slugrunner
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/updater
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/status
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/taffy
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/logaggregator
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/mariadb
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/flannel
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/postgresql
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/controller
INFO[11-14|15:49:06] pulled image                             host=grid2.flynn.stage.example.com name=flynn/blobstore
INFO[11-14|15:49:06] pulling latest binaries and config on all hosts
INFO[11-14|15:49:06] pulling binaries and config              host=grid2.flynn.stage.example.com
INFO[11-14|15:49:06] pulling binaries and config              host=grid1.flynn.stage.example.com
INFO[11-14|15:49:06] pulling binaries and config              host=grid3.flynn.stage.example.com
INFO[11-14|15:49:08] binaries and config pulled successfully  host=grid1.flynn.stage.example.com
INFO[11-14|15:49:08] binaries and config pulled successfully  host=grid3.flynn.stage.example.com
INFO[11-14|15:49:08] binaries and config pulled successfully  host=grid2.flynn.stage.example.com
INFO[11-14|15:49:08] validating binaries
INFO[11-14|15:49:08] updating flynn-host daemon on all hosts
INFO[11-14|15:49:09] flynn-host updated successfully          host=grid1.flynn.stage.example.com
INFO[11-14|15:49:09] flynn-host updated successfully          host=grid3.flynn.stage.example.com
INFO[11-14|15:49:10] flynn-host updated successfully          host=grid2.flynn.stage.example.com
<------ Hangs over here
```

It seems that the postgres can't sync data from old containers into the new version containers?
```
$ flynn -c stage -a postgres ps
ID                                                                    TYPE      STATE  CREATED         RELEASE
grid1.flynn.stage.example.com-d838f69c-2597-4400-b51e-aab8a3b5258f  postgres  up     9 weeks ago     63c9a9ab-f758-4eea-8fcd-e34d908406ef
grid1.flynn.stage.example.com-3624aaa0-7bb8-40c0-85f0-ca1d63b811f7  web       up     9 weeks ago     63c9a9ab-f758-4eea-8fcd-e34d908406ef
grid2.flynn.stage.example.com-af7e2a02-fc83-4fa0-be11-7421a24fee2a  postgres  up     9 weeks ago     63c9a9ab-f758-4eea-8fcd-e34d908406ef
grid3.flynn.stage.example.com-16fca67b-d286-484f-a8c1-a842652288ba  web       up     9 weeks ago     63c9a9ab-f758-4eea-8fcd-e34d908406ef
grid3.flynn.stage.example.com-f0e3cbf7-7a09-49dc-b4e4-7e5638214f5d  postgres  up     9 weeks ago     63c9a9ab-f758-4eea-8fcd-e34d908406ef
grid2.flynn.stage.example.com-94acbec1-29c0-40a1-83c7-a6015c6f2737  postgres  up     52 minutes ago  5ef46701-8a90-440a-9a42-e5f05c1f5b1c
```

**Comment by philiplb** [comment]
Today, after a long time, I tried the updater again to see in what state it is. It failed at deploying the postgres application. Here are the logs of it:
https://www.philiplb.de/misc/2017-02-22.flynn-host-debug.tar.gz

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
