### ISSUE TITLE
Panic when configuring Digital Ocean installation

### ISSUE THREAD

**Issue by lukeasrodgers** [flynn/flynn#2535]
I attempted to configure a DO cluster, which failed (`no such host` error for `api.digitalocean.com`).

After retrying with different account name and same API key, I am now seeing the following in the output from `flynn install`:

```
http: panic serving 127.0.0.1:52315: runtime error: invalid memory address or nil pointer dereference
goroutine 88 [running]:
net/http.func·011()
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1130 +0xbb
github.com/flynn/flynn/installer.(*Installer).ListDigitalOceanRegions(0x209351040, 0x2093dd500, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/installer/installer.go:260 +0x141
github.com/flynn/flynn/installer.(*httpAPI).GetCloudRegions(0x2093c2280, 0x22092f8188, 0x20967fb80, 0x2096ead00, 0x0, 0x0, 0x0)
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/installer/http.go:333 +0x395
github.com/flynn/flynn/installer.*httpAPI.GetCloudRegions·fm(0x22092f8188, 0x20967fb80, 0x2096ead00, 0x0, 0x0, 0x0)
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/installer/http.go:97 +0x63
github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x2093d39c0, 0x22092f8188, 0x20967fb80, 0x2096ead00)
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/Godeps/_workspace/src/github.com/julienschmidt/httprouter/router.go:276 +0x188
github.com/flynn/flynn/pkg/cors.func·001(0x22092f8188, 0x20967fb80, 0x2096ead00)
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/pkg/cors/cors.go:143 +0x288
net/http.HandlerFunc.ServeHTTP(0x2093be100, 0x22092f8188, 0x20967fb80, 0x2096ead00)
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1265 +0x41
net/http.serverHandler.ServeHTTP(0x2093193e0, 0x22092f8188, 0x20967fb80, 0x2096ead00)
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0x20967f360)
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /tmp/tmp.nvZjhkv9rt/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1751 +0x35e
```

The region and size dropdowns on the installation page show no options, and aren't clickable.

<img width="275" alt="screen shot 2016-03-06 at 10 56 58 pm" src="https://cloud.githubusercontent.com/assets/816444/13560566/cfeb88f2-e3ee-11e5-8993-13c6a88da3dd.png">

I'm not sure if the `no such host` error was related or not. Pinging `api.digitalocean.com` worked just fine.

OSX 10.10.5
```
luke@Lukes-MBP ~$ flynn version
v20160301.1
luke@Lukes-MBP ~$ uname -a
Darwin Lukes-MBP.fios-router.home 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
```

**Comment by titanous** [comment]
The no such host error might be #2508.

**Comment by lukeasrodgers** [comment]
@titanous is there an easy way to verify that that's the problem? I am moderately comfortable with wireshark if a packet capture would help.
Thanks

**Comment by titanous** [comment]
@lukeasrodgers Check the DNS config in your network preferences. If there is a search path, delete it and try again.

**Comment by lukeasrodgers** [comment]
Thanks @titanous that appears to have worked. For others encountering this issue: you may have to manually clear out both search paths *and* DNS servers using the commandline, e.g.:

```sh
# clear custom DNS servers
networksetup -setdnsservers Wi-Fi
# or, use Google's public DNS servers
networksetup -setdnsservers Wi-Fi 8.8.8.8
```
