### ISSUE TITLE
update fails with sirenia cluster in unhealthy state (too few asyncs)

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2653]
When running `flynn-host update` it stops at 

```
INFO[04-01|15:11:46] starting deploy of system app            name=postgres
EROR[04-01|15:11:56] error deploying app                      name=postgres err="sirenia cluster in unhealthy state (too few asyncs)"
```

then if I try `flynn-host fix --min-hosts 3` I get this error

```
INFO[04-01|15:12:56] getting postgres status 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x29 pc=0x6e90f8]

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc20806e870, 0x0, 0x0, 0x0, 0xa98b20, 0xc20802a050)
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x12e
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x73
github.com/flynn/flynn/host/fixer.(*ClusterFixer).FixPostgres(0xc20806e9f0, 0x0, 0x0)
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/host/fixer/fixer.go:394 +0x5b8
github.com/flynn/flynn/host/fixer.(*ClusterFixer).Run(0xc20806e9f0, 0xc2080d15c0, 0xc2080d1620, 0x0, 0x0)
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/host/fixer/fixer.go:117 +0x164f
github.com/flynn/flynn/host/fixer.*ClusterFixer.Run·fm(0xc2080d15c0, 0xc2080d1620, 0x0, 0x0)
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/host/cli/fix.go:8 +0x4d
github.com/flynn/flynn/host/cli.Run(0x7ffd070f58d0, 0x3, 0xc2080bf7c0, 0x2, 0x2, 0x0, 0x0)
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/host/cli/cli.go:57 +0x441
main.main()
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/host/host.go:134 +0x8c1

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc20806e870)
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x158
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.qs9JxQWgxZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xa8

goroutine 10 [IO wait]:
net.(*pollDesc).Wait(0xc2080da4c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080da4c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080da460, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7fbfe5642c88, 0xc2081a1fb8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038698, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fbfe5645b90, 0xc208038698, 0xc20804e108, 0xc20800f000, 0x1000, 0x1000, 0xa160c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080d1760, 0xc20800f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208046e40)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208046e40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20804e0b0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc20804e0b0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 13 [IO wait]:
net.(*pollDesc).Wait(0xc2080da5a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080da5a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080da540, 0xc2080dd000, 0x1000, 0x1000, 0x0, 0x7fbfe5642c88, 0xc2081a7a28)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080380d0, 0xc2080dd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fbfe5645b90, 0xc2080380d0, 0xc20804e3c8, 0xc2080dd000, 0x1000, 0x1000, 0xa160c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080d0640, 0xc2080dd000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208046600)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208046600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20804e370)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0xc20804e370)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc2080db800, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080db800, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080db7a0, 0xc20808f000, 0x1000, 0x1000, 0x0, 0x7fbfe5642c88, 0xc20815f798)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038678, 0xc20808f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fbfe5645b90, 0xc208038678, 0xc20804e1b8, 0xc20808f000, 0x1000, 0x1000, 0xa160c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc208143400, 0xc20808f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208046f60)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208046f60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20804e160)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0xc20804e160)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 20 [IO wait]:
net.(*pollDesc).Wait(0xc2080daa00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080daa00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080da9a0, 0xc208153000, 0x1000, 0x1000, 0x0, 0x7fbfe5642c88, 0xc20817aa68)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080380e8, 0xc208153000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fbfe5645b90, 0xc2080380e8, 0xc20804e318, 0xc208153000, 0x1000, 0x1000, 0xa160c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080e3700, 0xc208153000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208046b40)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208046b40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20804e2c0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 21 [select]:
net/http.(*persistConn).writeLoop(0xc20804e2c0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 23 [IO wait]:
net.(*pollDesc).Wait(0xc20818c0d0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20818c0d0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20818c070, 0xc208155000, 0x1000, 0x1000, 0x0, 0x7fbfe5642c88, 0xc2081a1690)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208038140, 0xc208155000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fbfe5645b90, 0xc208038140, 0xc20804e738, 0xc208155000, 0x1000, 0x1000, 0xa160c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20817df60, 0xc208155000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20814faa0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20814faa0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20804e6e0)
	/usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc20804e6e0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 26 [runnable]:
net/http.(*persistConn).readLoop(0xc20804e790)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 27 [select]:
net/http.(*persistConn).writeLoop(0xc20804e790)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by josephglanville** [comment]
Looks like the cluster may have already been somewhat damaged as the failed deploy came in only 10 seconds after being requested.

Can you try collect any logs you can with `flynn-host collect-debug-info` and describe your cluster, i.e number of nodes, how long it was running, have you ran the upgrade process before successfully etc.

**Comment by dottodot** [comment]
This is the first update on a 3 node cluster and it's been running about a month

Here's my debug info
node1 https://gist.github.com/096e884f186ab7ddc48ed5f19c5b3793
node2 https://gist.github.com/a79d93863262a52889842c45bd3020de
node3 https://gist.github.com/anonymous/5617191b6beb7446fbe98d03e0a3a62d

I also seem to have a high disk usage on node1 and when i run `df -h` I'm not sure it looks right.

```
Filesystem                                          Size  Used Avail Use% Mounted on
udev                                                483M   12K  483M   1% /dev
tmpfs                                                99M  684K   99M   1% /run
/dev/mapper/vg00-lv01                                37G   34G  1.9G  95% /
none                                                4.0K     0  4.0K   0% /sys/fs/cgroup
none                                                5.0M     0  5.0M   0% /run/lock
none                                                494M  3.3M  491M   1% /run/shm
none                                                100M     0  100M   0% /run/user
/dev/sda1                                           464M   98M  338M  23% /boot
flynn-default/e363b618-5b50-41a7-ade4-daf1f408040b   18G  256K   18G   1% /var/lib/flynn/volumes/zfs/mnt/e363b618-5b50-41a7-ade4-daf1f408040b
flynn-default/cd2cea6f-5f85-4b29-94c4-b0dc500e21b4   22G  3.9G   18G  18% /var/lib/flynn/volumes/zfs/mnt/cd2cea6f-5f85-4b29-94c4-b0dc500e21b4
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-da3fa3b6-23e2-43ef-b6d9-1b91db15f44a
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-e747bd69-7798-4fc4-9102-2218bede3f18
flynn-default/7a094f70-f723-4030-ac76-9c68590bb92e   18G     0   18G   0% /var/lib/flynn/volumes/zfs/mnt/7a094f70-f723-4030-ac76-9c68590bb92e
flynn-default/5a83c95a-6b7b-4414-a825-d8ed1176e719   18G     0   18G   0% /var/lib/flynn/volumes/zfs/mnt/5a83c95a-6b7b-4414-a825-d8ed1176e719
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-f04049d7-b249-44fa-bbde-e587f36138ce
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-78653648-6caa-4caa-b890-c820d2d4eca1
flynn-default/8adefcc9-8c58-41e2-ba36-f6033fdbfe11   22G  3.1G   18G  15% /var/lib/flynn/volumes/zfs/mnt/8adefcc9-8c58-41e2-ba36-f6033fdbfe11
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-c7524faa-c28f-4927-af56-35f1f5e9b72e
flynn-default/e441ba87-011e-4cb2-bfcc-6c4237699937   18G  256K   18G   1% /var/lib/flynn/volumes/zfs/mnt/e441ba87-011e-4cb2-bfcc-6c4237699937
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-aa1c79bd-c763-442b-a463-d315d0fde85d
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-78fd359c-41d7-4f07-9c07-512f9b4cb580
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-5fa4ab00-d66d-43a8-ae9e-31cfbf727015
flynn-default/8a69d296-bd23-4e0f-bbfc-f3b8c58e9d9c   18G  384K   18G   1% /var/lib/flynn/volumes/zfs/mnt/8a69d296-bd23-4e0f-bbfc-f3b8c58e9d9c
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-47038a52-0fcd-451b-b23e-643619577fe2
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-dc878478-66a2-4880-8f81-d1feb489f124
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-27f16a12-8247-436d-8fe8-df73095a4165
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-5154603d-58f2-4756-ab7b-ad7f5b9d2c06
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-9b4ba3d7-9cdc-4e3b-97bc-cc92addb16c4
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-ed3d1f6d-d950-4928-acd2-64b7e9df0091
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-ae02e986-253c-4403-85a6-db059e0b485c
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-e8a921f1-1863-4ce8-b04d-89d938a94d48
none                                                 37G   34G  1.9G  95% /var/lib/docker/aufs/mnt/tmp-cluster1-df70f499-6f23-4090-87d2-0300e726f049
flynn-default/8f8c1633-7d73-4aa8-bf74-4ab59bf3974f   18G     0   18G   0% /var/lib/flynn/volumes/zfs/mnt/8f8c1633-7d73-4aa8-bf74-4ab59bf3974f
flynn-default/5d00d59b-75e8-4241-87b8-1310320e910f   18G     0   18G   0% /var/lib/flynn/volumes/zfs/mnt/5d00d59b-75e8-4241-87b8-1310320e910f
flynn-default/d2028e34-3a8f-412a-836a-51d2656178fc   18G     0   18G   0% /var/lib/flynn/volumes/zfs/mnt/d2028e34-3a8f-412a-836a-51d2656178fc
```

**Comment by titanous** [comment]
@josephglanville I fixed the panics, but they were just a symptom of the sirenia status not including database details. Also, I think there was a failed discoverd upgrade.

**Comment by dottodot** [comment]
So what does this mean in terms of fixing my cluster?

**Comment by titanous** [comment]
@dottodot Did you take a backup before attempting the upgrade? The best option is to start a fresh cluster.

**Comment by dottodot** [comment]
Yes I've done a backup. Am I doing something wrong as this will be second time I've had to build a new cluster.

**Comment by titanous** [comment]
Building a new cluster is the recommended method to update Flynn. The in-place updater is still in beta and has a lot of moving parts, so we're still working the kinks out.

**Comment by SalvoLunar** [comment]
I've built a new cluster from a backup but I'm still getting the error "sirenia cluster in unhealthy state (too few asyncs)" when trying to change the limits for mariadb.

What can I do to fix it?
