### ISSUE TITLE
scheduler: Panic when stopping surplus omni jobs.

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#2705]
```
t=2016-04-16T13:29:59+0000 lvl=info msg="handling formation change" component=scheduler fn=HandleFormationChange app.id=288a2c03-585c-45bf-a42b-72aea39a660a release.id=05336755-107d-484a-93f9-95cd98e3eb80 processes=map[app:1]
t=2016-04-16T13:29:59+0000 lvl=info msg="handling formation change" component=scheduler fn=HandleFormationChange app.id=288a2c03-585c-45bf-a42b-72aea39a660a release.id=dbc6d65c-188f-4e87-a9ad-da5301a7358d processes=map[app:-1]
t=2016-04-16T13:29:59+0000 lvl=info msg="updating processes and tags of existing formation" component=scheduler fn=handleFormation app.id=288a2c03-585c-45bf-a42b-72aea39a660a release.id=dbc6d65c-188f-4e87-a9ad-da5301a7358d processes=map[app:-1] tags=map[]
t=2016-04-16T13:29:59+0000 lvl=info msg="scheduler loop exited" component=scheduler fn=Run
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.(*Scheduler).stopSurplusOmniJobs(0xc208001200, 0xc208126d20)
    /home/jpg/src/flynn/controller/scheduler/scheduler.go:604 +0xbf4
main.(*Scheduler).RectifyFormation(0xc208001200, 0xc20812c6c0, 0x24, 0xc20812c720, 0x24)
    /home/jpg/src/flynn/controller/scheduler/scheduler.go:560 +0x3dc
main.(*Scheduler).HandleRectify(0xc208001200, 0x0, 0x0)
    /home/jpg/src/flynn/controller/scheduler/scheduler.go:541 +0xbf
main.(*Scheduler).Run(0xc208001200, 0x0, 0x0)
    /home/jpg/src/flynn/controller/scheduler/scheduler.go:366 +0xaef
main.main()
    /home/jpg/src/flynn/controller/scheduler/scheduler.go:158 +0xd33
```

**Comment by lmars** [comment]
So this happens when a deployment incorrectly calculates how many omni jobs need stopping and sets a negative value for the count (observed in CI).

We should do two things:

* Ensure formations always have non-negative counts
* Fix deploys so they do the correct calculations when old scale is not as expected (e.g. if an omni type is scaled to 1, there are 3 hosts, and the old release has 2 running jobs, the deploy should only wait for 2 down events, but currently it waits for 3 because that's how many new jobs it starts, see [here](https://github.com/flynn/flynn/blob/v20160423.0/controller/worker/deployment/one_by_one.go#L52-L99))
