### ISSUE TITLE
Unable to reach AWS endpoints

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#2775]
CC @temujin9 @ohhatiya

One of our users reported the following error:
```
21:37:50.731Z  INFO srd-generator-services:
    UnknownEndpoint: Inaccessible host: `sqs.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region.
        at Request.ENOTFOUND_ERROR (/app/node_modules/aws-sdk/lib/event_listeners.js:399:46)
        at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
        at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
        at Request.emit (/app/node_modules/aws-sdk/lib/request.js:595:14)
        at ClientRequest.error (/app/node_modules/aws-sdk/lib/event_listeners.js:228:22)
        at ClientRequest.<anonymous> (/app/node_modules/aws-sdk/lib/http/node.js:62:19)
        at emitOne (events.js:95:20)
        at ClientRequest.emit (events.js:182:7)
        at TLSSocket.socketErrorListener (_http_client.js:262:9)
        at emitOne (events.js:90:13)
```
We are also getting problems reaching the Datadog endpoint. We suspect it's the same issue.
```
[Error: getaddrinfo ENOTFOUND app.datadoghq.com app.datadoghq.com:443]
```

With a little googling, it seems like other people have run into this issue while working with Docker containers (https://github.com/aws/aws-sdk-js/issues/528). We suspect it's a networking issue on the container. Unfortunately, I don't have enough insight into how flynn networking works to guess at what may be causing the issue.

I have collected the logs from the clusters here - https://bazaarvoice.box.com/s/s04c0mjw8nr8rcx0sp5isev91w5tyjda

Let me know if you need me to grab additional logging to help debug this issue.

**Comment by titanous** [comment]
Containers are configured with discoverd as the only resolver, discoverd in turn upstreams all requests for hosts not ending in `.discoverd.` to the resolvers configured in `/etc/resolv.conf`. Is this an ongoing issue? If so, can you replicate it on the host?

**Comment by tianx2** [comment]
@titanous i don't think it's an ongoing issue, but if it happens again I'll know where to look. Thanks for that explanation. The user seeing the issue doesn't think they can replicate the issue. It's more like "it will eventually happen" type of feeling. This probably needs go through a log analyzer to find a definitive problem.

**Comment by titanous** [comment]
Based on the logs and what I know about DNS handling in Flynn, my assessment is that the likely cause of this issue was a transient outage of the AWS DNS server configured on the host.

**Comment by tianx2** [comment]
Closing the ticket. Will re-open if it happens again.
