### ISSUE TITLE
MariaDB appliance went down completely

### ISSUE THREAD

**Issue by michaelyork** [flynn/flynn#3313]
Shows down in the health dashboard as well. Logs sent to logs@.

This looks suspicious from some of the process logs:

```
[2016-08-19T15:42:08.158578173Z] t=2016-08-19T15:42:08+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:42:38.141981736Z] t=2016-08-19T15:42:38+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="unknown_error: Something went wrong"
[2016-08-19T15:42:38.142166176Z] t=2016-08-19T15:42:38+0000 lvl=info msg="skipping config apply, no changes" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:42:38.144405264Z] t=2016-08-19T15:42:38+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:42:38.145326496Z] t=2016-08-19T15:42:38+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:42:38.148106394Z] t=2016-08-19T15:42:38+0000 lvl=dbug msg="new peer" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:42:38.150204334Z] t=2016-08-19T15:42:38+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:44:07.934841892Z] t=2016-08-19T15:44:07+0000 lvl=eror msg="error streaming backup" app=mariadb component=http err="write tcp 100.100.14.62:3307->100.100.5.0:60814: write: connection reset by peer"
[2016-08-19T15:44:54.362105109Z] 2016-08-19 15:44:54 140547060611840 [Note] Start binlog_dump to slave_server(1684276561), pos(, 4)
[2016-08-19T15:44:54.450073848Z] 2016-08-19 15:44:54 140547060611840 [Note] Start semi-sync binlog_dump to slave (server_id: 1684276561), pos(, 4)
[2016-08-19T15:45:10.464026393Z] 2016-08-19 15:45:10 140547194555136 [Note] Stop semi-sync binlog_dump to slave (server_id: 1684288298)
[2016-08-19T15:45:10.464131836Z] 2016-08-19 15:45:10 140547194555136 [Warning] Aborted connection 55 to db: 'unconnected' user: 'flynn' host: '100.100.51.0' (Got an error writing communication packets)
[2016-08-19T15:45:54.789213751Z] t=2016-08-19T15:45:54+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=2
[2016-08-19T15:45:54.793606987Z] t=2016-08-19T15:45:54+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=1
[2016-08-19T15:45:54.794341928Z] t=2016-08-19T15:45:54+0000 lvl=info msg="reconfiguring database" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:45:54.795684076Z] t=2016-08-19T15:45:54+0000 lvl=info msg="nothing to do" app=mariadb fn=reconfigure reason="config already applied"
[2016-08-19T15:45:54.800637662Z] t=2016-08-19T15:45:54+0000 lvl=dbug msg="skipping start, already online" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:45:54.802466172Z] t=2016-08-19T15:45:54+0000 lvl=info msg="applied database config" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:45:54.805808346Z] t=2016-08-19T15:45:54+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:45:54.827935045Z] t=2016-08-19T15:45:54+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:45:54.836582654Z] t=2016-08-19T15:45:54+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:45:54.841497787Z] t=2016-08-19T15:45:54+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:45:54.851855936Z] t=2016-08-19T15:45:54+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=0
[2016-08-19T15:45:54.856673932Z] t=2016-08-19T15:45:54+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:45:54.865248025Z] t=2016-08-19T15:45:54+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:45:54.89370086Z]  t=2016-08-19T15:45:54+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:45:54.896559018Z] t=2016-08-19T15:45:54+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:45:54.899541669Z] t=2016-08-19T15:45:54+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:45:54.905212169Z] t=2016-08-19T15:45:54+0000 lvl=info msg="skipping config apply, no changes" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:45:54.911865791Z] t=2016-08-19T15:45:54+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:45:54.916378373Z] t=2016-08-19T15:45:54+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:45:54.959124156Z] t=2016-08-19T15:45:54+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:45:54.959799493Z] t=2016-08-19T15:45:54+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:15.510355034Z] t=2016-08-19T15:46:15+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:15.540147824Z] t=2016-08-19T15:46:15+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=1
[2016-08-19T15:46:15.545858642Z] t=2016-08-19T15:46:15+0000 lvl=info msg="skipping config apply, no changes" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:46:15.553071258Z] t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.555322382Z] t=2016-08-19T15:46:15+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:15.557564861Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:15.559710401Z] t=2016-08-19T15:46:15+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:15.561821525Z] t=2016-08-19T15:46:15+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:15.562635562Z] t=2016-08-19T15:46:15+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=2
[2016-08-19T15:46:15.56364031Z]  t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.564450996Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:15.564991946Z] t=2016-08-19T15:46:15+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:15.566142029Z] t=2016-08-19T15:46:15+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:15.566634508Z] t=2016-08-19T15:46:15+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=3
[2016-08-19T15:46:15.567501424Z] t=2016-08-19T15:46:15+0000 lvl=info msg="skipping config apply, no changes" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:46:15.568430002Z] t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.569244599Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="at rest" app=mariadb component=peer fn=rest
[2016-08-19T15:46:15.569711437Z] t=2016-08-19T15:46:15+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=2
[2016-08-19T15:46:15.572048228Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg=moving app=mariadb component=peer
[2016-08-19T15:46:15.572215319Z] t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.573030484Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:15.573515269Z] t=2016-08-19T15:46:15+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:15.574579462Z] t=2016-08-19T15:46:15+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:15.57590912Z]  t=2016-08-19T15:46:15+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=1
[2016-08-19T15:46:15.577948682Z] t=2016-08-19T15:46:15+0000 lvl=info msg="skipping config apply, no changes" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:46:15.57868884Z]  t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.579443882Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:15.580191122Z] t=2016-08-19T15:46:15+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:15.580870812Z] t=2016-08-19T15:46:15+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:15.581902077Z] t=2016-08-19T15:46:15+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=0
[2016-08-19T15:46:15.583394469Z] t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.583933446Z] t=2016-08-19T15:46:15+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:15.584692997Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:15.585612196Z] t=2016-08-19T15:46:15+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:15.586501227Z] t=2016-08-19T15:46:15+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:15.587183878Z] t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.587844557Z] t=2016-08-19T15:46:15+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:15.588582041Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:15.58932174Z]  t=2016-08-19T15:46:15+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:15.590143874Z] t=2016-08-19T15:46:15+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:15.591077494Z] t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.59228341Z]  t=2016-08-19T15:46:15+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:15.593479645Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:15.593779253Z] t=2016-08-19T15:46:15+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:15.594331179Z] t=2016-08-19T15:46:15+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:15.595181288Z] t=2016-08-19T15:46:15+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:15.595838721Z] t=2016-08-19T15:46:15+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:15.596702552Z] t=2016-08-19T15:46:15+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:15.597607318Z] t=2016-08-19T15:46:15+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:22.094374992Z] t=2016-08-19T15:46:22+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:22.094467778Z] t=2016-08-19T15:46:22+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=1
[2016-08-19T15:46:22.100314986Z] t=2016-08-19T15:46:22+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:22.105183458Z] t=2016-08-19T15:46:22+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:22.13249817Z]  t=2016-08-19T15:46:22+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:22.138588498Z] t=2016-08-19T15:46:22+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:26.999489223Z] t=2016-08-19T15:46:26+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:27.001891296Z] t=2016-08-19T15:46:27+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=2
[2016-08-19T15:46:27.001996841Z] t=2016-08-19T15:46:27+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:27.005452685Z] t=2016-08-19T15:46:27+0000 lvl=dbug msg="preparing for new generation" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:27.009388125Z] t=2016-08-19T15:46:27+0000 lvl=info msg="starting takeover" app=mariadb component=peer fn=startTakeoverWithPeer reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:27.025066068Z] t=2016-08-19T15:46:27+0000 lvl=info msg="declaring new generation" app=mariadb component=peer fn=startTakeoverWithPeer reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:27.042787756Z] t=2016-08-19T15:46:27+0000 lvl=eror msg="failed to declare new generation, backing off" app=mariadb component=peer fn=startTakeoverWithPeer reason="sync gone" min_wal=0-1684278846-1986137 err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:27.044496506Z] t=2016-08-19T15:46:27+0000 lvl=info msg="got discoverd state" app=mariadb component=peer fn=handleDiscoverdState index=4752 state=true
[2016-08-19T15:46:27.044585481Z] t=2016-08-19T15:46:27+0000 lvl=info msg="already have this state" app=mariadb component=peer fn=handleDiscoverdState index=4752
[2016-08-19T15:46:27.046040114Z] t=2016-08-19T15:46:27+0000 lvl=info msg="skipping config apply, no changes" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:46:27.048435677Z] t=2016-08-19T15:46:27+0000 lvl=dbug msg="at rest" app=mariadb component=peer fn=rest
[2016-08-19T15:46:27.051144924Z] t=2016-08-19T15:46:27+0000 lvl=info msg="got discoverd state" app=mariadb component=peer fn=handleDiscoverdState index=4760 state=true
[2016-08-19T15:46:27.051236192Z] t=2016-08-19T15:46:27+0000 lvl=info msg="already have this state" app=mariadb component=peer fn=handleDiscoverdState index=4760
[2016-08-19T15:46:27.054506267Z] t=2016-08-19T15:46:27+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=1
[2016-08-19T15:46:27.057563249Z] t=2016-08-19T15:46:27+0000 lvl=dbug msg=moving app=mariadb component=peer
[2016-08-19T15:46:27.058551178Z] t=2016-08-19T15:46:27+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:27.06001928Z]  t=2016-08-19T15:46:27+0000 lvl=dbug msg="preparing for new generation" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:27.062608669Z] t=2016-08-19T15:46:27+0000 lvl=info msg="starting takeover" app=mariadb component=peer fn=startTakeoverWithPeer reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:27.063387053Z] t=2016-08-19T15:46:27+0000 lvl=info msg="declaring new generation" app=mariadb component=peer fn=startTakeoverWithPeer reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:27.109970126Z] t=2016-08-19T15:46:27+0000 lvl=eror msg="failed to declare new generation, backing off" app=mariadb component=peer fn=startTakeoverWithPeer reason="sync gone" min_wal=0-1684278846-1986137 err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:27.111715922Z] t=2016-08-19T15:46:27+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=0
[2016-08-19T15:46:27.113369085Z] t=2016-08-19T15:46:27+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:27.113440375Z] t=2016-08-19T15:46:27+0000 lvl=warn msg="would takeover but no async peers present" app=mariadb component=peer fn=startTakeover reason="sync gone" min_wal=0-1684278846-1986137
[2016-08-19T15:46:27.114729087Z] t=2016-08-19T15:46:27+0000 lvl=dbug msg="peer missing" app=mariadb component=peer fn=evalClusterState async.id=3e58898f-ae4c-497c-bcc4-0a45359736d1 async.addr=100.100.51.42:3306
[2016-08-19T15:46:27.116760373Z] t=2016-08-19T15:46:27+0000 lvl=info msg="updating list of asyncs" app=mariadb component=peer fn=startUpdateAsyncs
[2016-08-19T15:46:31.124224642Z] t=2016-08-19T15:46:31+0000 lvl=eror msg="failed to update cluster state" app=mariadb component=peer fn=startUpdateAsyncs err="precondition_failed: Service metadata for \"mariadb\" exists, but wrong index provided"
[2016-08-19T15:46:31.126484633Z] t=2016-08-19T15:46:31+0000 lvl=info msg="got discoverd state" app=mariadb component=peer fn=handleDiscoverdState index=4778 state=true
[2016-08-19T15:46:31.126563723Z] t=2016-08-19T15:46:31+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:31.127862497Z] t=2016-08-19T15:46:31+0000 lvl=info msg="assuming deposed role" app=mariadb component=peer role=deposed fn=assumeDeposed
[2016-08-19T15:46:31.129397351Z] t=2016-08-19T15:46:31+0000 lvl=info msg="reconfiguring database" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:46:31.131479498Z] t=2016-08-19T15:46:31+0000 lvl=info msg="nothing to do" app=mariadb fn=reconfigure reason="null role"
[2016-08-19T15:46:31.131562964Z] t=2016-08-19T15:46:31+0000 lvl=dbug msg="stopping database" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:46:31.136642038Z] t=2016-08-19T15:46:31+0000 lvl=info msg="stopping mysql" app=mariadb fn=stop
[2016-08-19T15:46:31.137612254Z] t=2016-08-19T15:46:31+0000 lvl=dbug msg="stopping daemon" app=mariadb fn=stop
[2016-08-19T15:46:31.1619207Z]   t=2016-08-19T15:46:31+0000 lvl=info msg="applied database config" app=mariadb component=peer fn=applyConfig
[2016-08-19T15:46:31.16206848Z]  t=2016-08-19T15:46:31+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=1
[2016-08-19T15:46:31.164293449Z] t=2016-08-19T15:46:31+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-08-19T15:46:31.164580691Z] panic: unexpected role deposed
[2016-08-19T15:46:31.186924171Z] goroutine 13 [running]:
[2016-08-19T15:46:31.191076048Z] panic(0x7bb6a0, 0xc82039a020)
[2016-08-19T15:46:31.192647082Z]    /usr/local/go/src/runtime/panic.go:481 +0x3e6
[2016-08-19T15:46:31.19575753Z]  github.com/flynn/flynn/pkg/sirenia/state.(*Peer).evalClusterState(0xc8201340f0)
[2016-08-19T15:46:31.197961279Z]    /tmp/tmp.ayEuUtwt6g/src/github.com/flynn/flynn/pkg/sirenia/state/state.go:592 +0x134c
[2016-08-19T15:46:31.20114314Z]  github.com/flynn/flynn/pkg/sirenia/state.(*Peer).Run(0xc8201340f0)
[2016-08-19T15:46:31.203873103Z]    /tmp/tmp.ayEuUtwt6g/src/github.com/flynn/flynn/pkg/sirenia/state/state.go:297 +0x2eb
[2016-08-19T15:46:31.20482714Z]  created by main.main
[2016-08-19T15:46:31.20597938Z]     /tmp/tmp.ayEuUtwt6g/src/github.com/flynn/flynn/appliance/mariadb/cmd/flynn-mariadb/main.go:81 +0x13f6
```

**Comment by josephglanville** [comment]
Hi @michaelyork sorry this has languished for a little bit, we have been very busy looking into MariaDB issues. I'm looking into this one now.

Perchance did the MariaDB cluster recover form this state or did it remain inoperable?
