### ISSUE TITLE
flynn mongodb and mariadb problems

### ISSUE THREAD

**Issue by pdaniel-frk** [flynn/flynn#3403]
Hello,

I am trying to use mongodb provider and mariadb provider. It seems there is a problem with them. I have allot of crashing errors:

![image](https://cloud.githubusercontent.com/assets/10430333/18611979/55820154-7d54-11e6-9569-b70ac6b033ce.png)

and maria db

![image](https://cloud.githubusercontent.com/assets/10430333/18611983/6e9e85ea-7d54-11e6-9914-b82e7811a8f3.png)

Mongo db log :

[2016-09-18T00:23:20.654442282Z] 2016-09-18T00:23:20.642+0000 I NETWORK  [initandlisten] connection accepted from 100.100.39.29:54412 #47 (3 connections now open)
[2016-09-18T00:23:20.664140588Z] 2016-09-18T00:23:20.664+0000 I ACCESS   [conn47] Successfully authenticated as principal flynn on admin
[2016-09-18T00:23:20.664925313Z] 2016-09-18T00:23:20.664+0000 I COMMAND  [conn47] terminating, shutdown command received
[2016-09-18T00:23:20.670947303Z] 2016-09-18T00:23:20.669+0000 I FTDC     [conn47] Shutting down full-time diagnostic data capture
[2016-09-18T00:23:20.672043137Z] 2016-09-18T00:23:20.672+0000 I REPL     [conn47] Stopping replication applier threads
[2016-09-18T00:23:21.7556386Z]   2016-09-18T00:23:21.755+0000 I CONTROL  [conn47] now exiting
[2016-09-18T00:23:21.755717502Z] 2016-09-18T00:23:21.755+0000 I NETWORK  [conn47] shutdown: going to close listening sockets...
[2016-09-18T00:23:21.756192717Z] 2016-09-18T00:23:21.755+0000 I NETWORK  [conn47] closing listening socket: 5
[2016-09-18T00:23:21.757285252Z] 2016-09-18T00:23:21.755+0000 I NETWORK  [conn47] closing listening socket: 6
[2016-09-18T00:23:21.757394055Z] 2016-09-18T00:23:21.757+0000 I NETWORK  [conn47] removing socket file: /tmp/mongodb-27017.sock
[2016-09-18T00:23:21.758711997Z] 2016-09-18T00:23:21.758+0000 I NETWORK  [conn47] shutdown: going to flush diaglog...
[2016-09-18T00:23:21.758791799Z] 2016-09-18T00:23:21.758+0000 I NETWORK  [conn47] shutdown: going to close sockets...
[2016-09-18T00:23:21.760222944Z] 2016-09-18T00:23:21.759+0000 I STORAGE  [conn47] WiredTigerKVEngine shutting down
[2016-09-18T00:23:21.761795094Z] 2016-09-18T00:23:21.761+0000 I NETWORK  [conn45] end connection 100.100.39.29:54388 (2 connections now open)
[2016-09-18T00:23:21.868439655Z] 2016-09-18T00:23:21.868+0000 I STORAGE  [conn47] shutdown: removing fs lock...
[2016-09-18T00:23:21.86923378Z]  2016-09-18T00:23:21.868+0000 I CONTROL  [conn47] dbexit:  rc: 0
[2016-09-18T00:23:21.87207457Z]  t=2016-09-18T00:23:21+0000 lvl=info msg="database gracefully shutdown" app=mongodb fn=stop
[2016-09-18T00:23:21.87209847Z]  t=2016-09-18T00:23:21+0000 lvl=info msg="applied database config" app=mongodb component=peer fn=applyConfig
[2016-09-18T00:23:21.873079401Z] t=2016-09-18T00:23:21+0000 lvl=info msg="skipping config apply, no changes" app=mongodb component=peer fn=applyConfig
[2016-09-18T00:23:21.873926328Z] t=2016-09-18T00:23:21+0000 lvl=dbug msg="at rest" app=mongodb component=peer fn=rest
[2016-09-18T00:23:27.894818055Z] t=2016-09-18T00:23:27+0000 lvl=info msg="discoverd peers" app=mongodb component=peer peers=3
[2016-09-18T00:23:27.897163429Z] t=2016-09-18T00:23:27+0000 lvl=dbug msg=moving app=mongodb component=peer
[2016-09-18T00:23:27.897788849Z] t=2016-09-18T00:23:27+0000 lvl=info msg="starting state evaluation" app=mongodb component=peer fn=evalClusterState
[2016-09-18T00:23:27.900557336Z] panic: unexpected role deposed
[2016-09-18T00:23:27.901135054Z] goroutine 14 [running]:
[2016-09-18T00:23:27.901604168Z] panic(0x7e9460, 0xc820202640)
[2016-09-18T00:23:27.901894378Z]    /usr/local/go/src/runtime/panic.go:481 +0x3e6
[2016-09-18T00:23:27.902813506Z] github.com/flynn/flynn/pkg/sirenia/state.(_Peer).evalClusterState(0xc820134000)
[2016-09-18T00:23:27.903341323Z]    /tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/pkg/sirenia/state/state.go:592 +0x134c
[2016-09-18T00:23:27.903723935Z] github.com/flynn/flynn/pkg/sirenia/state.(_Peer).Run(0xc820134000)
[2016-09-18T00:23:27.904103347Z]    /tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/pkg/sirenia/state/state.go:297 +0x2eb
[2016-09-18T00:23:27.904302053Z] created by main.main
[2016-09-18T00:23:27.904792368Z]    /tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/appliance/mongodb/cmd/flynn-mongodb/main.go:87 +0x1617

and Maria db log : 

[2016-09-18T00:44:07.879397079Z] t=2016-09-18T00:44:07+0000 lvl=dbug msg="stopping daemon" app=mariadb fn=stop
[2016-09-18T00:44:07.88561118Z]  t=2016-09-18T00:44:07+0000 lvl=info msg="applied database config" app=mariadb component=peer fn=applyConfig
[2016-09-18T00:44:07.885726086Z] t=2016-09-18T00:44:07+0000 lvl=info msg="skipping config apply, no changes" app=mariadb component=peer fn=applyConfig
[2016-09-18T00:44:07.889401564Z] t=2016-09-18T00:44:07+0000 lvl=dbug msg="at rest" app=mariadb component=peer fn=rest
[2016-09-18T00:44:25.634978934Z] t=2016-09-18T00:44:25+0000 lvl=info msg="discoverd peers" app=mariadb component=peer peers=3
[2016-09-18T00:44:25.636538309Z] t=2016-09-18T00:44:25+0000 lvl=dbug msg=moving app=mariadb component=peer
[2016-09-18T00:44:25.636666415Z] t=2016-09-18T00:44:25+0000 lvl=info msg="starting state evaluation" app=mariadb component=peer fn=evalClusterState
[2016-09-18T00:44:25.639254238Z] panic: unexpected role deposed
[2016-09-18T00:44:25.641722556Z] goroutine 20 [running]:
[2016-09-18T00:44:25.64179626Z]  panic(0x7bb6a0, 0xc8203e8c40)
[2016-09-18T00:44:25.642594698Z]    /usr/local/go/src/runtime/panic.go:481 +0x3e6
[2016-09-18T00:44:25.643254429Z] github.com/flynn/flynn/pkg/sirenia/state.(_Peer).evalClusterState(0xc82011e0f0)
[2016-09-18T00:44:25.644124071Z]    /tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/pkg/sirenia/state/state.go:592 +0x134c
[2016-09-18T00:44:25.644635895Z] github.com/flynn/flynn/pkg/sirenia/state.(_Peer).Run(0xc82011e0f0)
[2016-09-18T00:44:25.645305827Z]    /tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/pkg/sirenia/state/state.go:297 +0x2eb
[2016-09-18T00:44:25.646404679Z] created by main.main
[2016-09-18T00:44:25.647579636Z]    /tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/appliance/mariadb/cmd/flynn-mariadb/main.go:81 +0x13f6

**Comment by josephglanville** [comment]
Please supply the debug logs captured with `flynn-host collect-debug-info`

**Comment by pdaniel-frk** [comment]
Here it is.

https://gist.github.com/ae70a5d17476f72a675f3242af3a5f38

After a complete restart of the entire cluster, nothing is working :)

**Comment by hugoleodev** [comment]
+1

**Comment by hugoleodev** [comment]
I'm experiencing the same problem.

**Comment by JMSwag** [comment]
I've emailed debug logs to the flynn contact email address.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
