### ISSUE TITLE
JDK version error when trying to run Play 1.4

### ISSUE THREAD

**Issue by dabeeeenster** [flynn/flynn#3520]
Getting 

       Exception in thread "main" java.lang.UnsupportedClassVersionError: play/deps/DependenciesManager : Unsupported major.minor version 51.0

When specifying 

````
require:
    - play 1.4.3
```

in dependencies.yml. Would I need to explicitly set the JDK version somewhere?

```
-----> Building playeg...
-----> Play! app detected
-----> Installing OpenJDK 1.6... done
-----> Updating Play! version. Previous version was 1.3.1. Updating to 1.4.3...
-----> Installing Play! 1.4.3.....
       Downloading play-1.4.3.zip from https://downloads.typesafe.com
       Preparing binary package...
       Done installing Play!
-----> Building Play! application...
       ~        _            _
       ~  _ __ | | __ _ _  _| |
       ~ | '_ | |/ _' | || |_|
       ~ |  __/|_|____|__ (_)
       ~ |_|            |__/
       ~
       ~ play! 1.4.3, https://www.playframework.com
       ~
       1.4.3
       Building Play! application at directory ./
       Resolving dependencies: .play/play dependencies ./ --forProd --forceCopy --silent -Duser.home=/tmp/build 2>&1
       Exception in thread "main" java.lang.UnsupportedClassVersionError: play/deps/DependenciesManager : Unsupported major.minor version 51.0
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
       at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
       Could not find the main class: play.deps.DependenciesManager. Program will exit.
       !     Failed to build Play! application

```

**Comment by titanous** [comment]
Yeah, it sounds like the runtime version is wrong, try specifying the version you want in a`system.properties` file in the root of the repo:

```text
java.runtime.version=1.8
```

**Comment by dabeeeenster** [comment]
Yep that fixed it - thanks. I guess the buildpack isn't clever enough to know the JDK dependency?

**Comment by titanous** [comment]
Apparently not.
