### ISSUE TITLE
Can't add mysql resource: unknown_error: Something went wrong

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3576]
**What I tried to do:**
I tried to add mariadb appliance to my application.

**What I got instead:**
```
$ flynn -c production -a project resource add mysql
unknown_error: Something went wrong
```

This has been working just fine before but now it fails everytime.

**Details**
```
$ flynn-host --version
v20160814.0
```

**Comment by josephglanville** [comment]
Please provide debug infomation captured by `flynn-host collect-debug-info`. If it's too large for gist please email to `logs@flynn.io` with `#3576` in the subject.

**Comment by onnimonni** [comment]
Whoa, this fails even though I have plenty of memory.
```
$ free -m
             total       used       free     shared    buffers     cached
Mem:          3953       1941       2011        150         10        374
-/+ buffers/cache:       1556       2396
Swap:            0          0          0
```

```
$ flynn-host collect-debug-info
INFO[10-26|12:03:24] uploading logs and debug information to a private, anonymous gist
INFO[10-26|12:03:24] this may take a while depending on the size of your logs
INFO[10-26|12:03:24] getting flynn-host logs
INFO[10-26|12:03:25] getting scheduler state
INFO[10-26|12:03:25] getting job logs
INFO[10-26|12:04:37] getting system information
EROR[10-26|12:04:37] error capturing output of "ps faux"      err="fork/exec /bin/ps: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "ifconfig"     err="fork/exec /sbin/ifconfig: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "uname -a"     err="fork/exec /bin/uname: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "lsb_release -a" err="fork/exec /usr/bin/lsb_release: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "date"         err="fork/exec /bin/date: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "free -m"      err="fork/exec /usr/bin/free: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "df -h"        err="fork/exec /bin/df: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "flynn-host version" err="fork/exec /usr/local/bin/flynn-host: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "route -n"     err="fork/exec /sbin/route: cannot allocate memory"
EROR[10-26|12:04:37] error capturing output of "iptables -L -v -n --line-numbers" err="fork/exec /sbin/iptables: cannot allocate memory"
INFO[10-26|12:04:37] Total size of 1024207394 bytes exceeds gist limit, falling back to tarball.
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf57d10, 0x16)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sysMap(0xc8a0f50000, 0x3040000, 0x476f00, 0x15b2a58)
	/usr/local/go/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0x1597080, 0x3040000, 0xc820000300)
	/usr/local/go/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0x1597080, 0x1820, 0x0)
	/usr/local/go/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0x1597080, 0x1819, 0x76754068)
	/usr/local/go/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0x1597080, 0x1819, 0x100000000, 0x7f13e133a4a0)
	/usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7f13deb02de8)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x1597080, 0x1819, 0x100000000, 0x1)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x3032000, 0x3, 0x7f13e133a4a0)
	/usr/local/go/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc820015500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc8200473c8 sp=0xc8200473c0
runtime.mallocgc(0x3032000, 0x0, 0x3, 0x0)
	/usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc8200474a0 sp=0xc8200473c8
runtime.rawbyteslice(0x3031288, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:302 +0xbb fp=0xc8200474f0 sp=0xc8200474a0
runtime.stringtoslicebyte(0x0, 0xc854ed4000, 0x3031288, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:144 +0x11e fp=0xc820047558 sp=0xc8200474f0
github.com/flynn/flynn/host/cli.(*Gist).CreateTarball(0xc8200e8e40, 0xc821f57280, 0x36, 0x0, 0x0)
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/host/cli/gist.go:126 +0x59d fp=0xc8200477d8 sp=0xc820047558
github.com/flynn/flynn/host/cli.runCollectDebugInfo(0xc8202bad20, 0x0, 0x0)
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/host/cli/collect-debug-info.go:101 +0x13ce fp=0xc820047b20 sp=0xc8200477d8
github.com/flynn/flynn/host/cli.Run(0x7ffdb0b77d44, 0x12, 0x15b0210, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x60c fp=0xc820047c40 sp=0xc820047b20
main.main()
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/host/host.go:145 +0xb38 fp=0xc820047f40 sp=0xc820047c40
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820047f90 sp=0xc820047f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820047f98 sp=0xc820047f90

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive, 1 minutes]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc820011440)
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x177
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xc3

goroutine 18 [select, 1 minutes, locked to thread]:
runtime.gopark(0x106c9b8, 0xc82001c728, 0xeaa1d8, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82001c728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82001c728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 11 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f13e13faef8, 0x72, 0xc82176f000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82013ea00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82013ea00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82013e9a0, 0xc82176f000, 0x1000, 0x1000, 0x0, 0x7f13e1475168, 0xc82000c018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820024040, 0xc82176f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f13e1437a00, 0xc820024040, 0xc8202077f8, 0xc82176f000, 0x1000, 0x1000, 0x449883, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc821729e20, 0xc82176f000, 0x1000, 0x1000, 0xc820e94d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8215e9da0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8215e9da0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820207790)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 37 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f13e13fb2b8, 0x72, 0xc82025d000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201e8370, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e8370, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201e8310, 0xc82025d000, 0x1000, 0x1000, 0x0, 0x7f13e1475168, 0xc82000c018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82023e008, 0xc82025d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f13e1437a00, 0xc82023e008, 0xc8200ca548, 0xc82025d000, 0x1000, 0x1000, 0x449883, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc82023c140, 0xc82025d000, 0x1000, 0x1000, 0xc820031d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc82005a3c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82005a3c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200ca4e0)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 35 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f13e13fb378, 0x72, 0xc820080000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201e81b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e81b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201e8150, 0xc820080000, 0x1000, 0x1000, 0x0, 0x7f13e1475168, 0xc82000c018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82023e4c8, 0xc820080000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f13e1437a00, 0xc82023e4c8, 0xc8200ca3a8, 0xc820080000, 0x1000, 0x1000, 0x449883, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc82023c080, 0xc820080000, 0x1000, 0x1000, 0xc820149d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc82005a120)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82005a120, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200ca340)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 36 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200ca340)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 38 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200ca4e0)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 27 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f13e13fb1f8, 0x72, 0xc82014b000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201e84c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e84c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201e8460, 0xc82014b000, 0x1000, 0x1000, 0x0, 0x7f13e1475168, 0xc82000c018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820202028, 0xc82014b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f13e1437a00, 0xc820202028, 0xc8200ca478, 0xc82014b000, 0x1000, 0x1000, 0x449883, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8201753c0, 0xc82014b000, 0x1000, 0x1000, 0xc820033d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8200e4960)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200e4960, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200ca410)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 28 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200ca410)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 51 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f13e13fb138, 0x72, 0xc820884000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820161090, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820161090, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820161030, 0xc820884000, 0x1000, 0x1000, 0x0, 0x7f13e1475168, 0xc82000c018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82023e040, 0xc820884000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f13e1437a00, 0xc82023e040, 0xc82005dcd8, 0xc820884000, 0x1000, 0x1000, 0x449883, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc820861ae0, 0xc820884000, 0x1000, 0x1000, 0xc820146d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc82077d800)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82077d800, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82005dc70)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 52 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc82005dc70)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 54 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f13e13fb078, 0x72, 0xc820e8c000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820161b10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820161b10, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820161ab0, 0xc820e8c000, 0x1000, 0x1000, 0x0, 0x7f13e1475168, 0xc82000c018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82023e058, 0xc820e8c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f13e1437a00, 0xc82023e058, 0xc8202070a8, 0xc820e8c000, 0x1000, 0x1000, 0x449883, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc820e65ec0, 0xc820e8c000, 0x1000, 0x1000, 0xc820e97d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820de6ea0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820de6ea0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820207040)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 55 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc820207040)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 9 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f13e13fafb8, 0x72, 0xc820e9b000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820156d10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820156d10, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820156cb0, 0xc820e9b000, 0x1000, 0x1000, 0x0, 0x7f13e1475168, 0xc82000c018)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820024028, 0xc820e9b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f13e1437a00, 0xc820024028, 0xc820245318, 0xc820e9b000, 0x1000, 0x1000, 0x449883, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc821729d80, 0xc820e9b000, 0x1000, 0x1000, 0xc820e93d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8215e9c20)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8215e9c20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8202452b0)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 10 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8202452b0)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 12 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc820207790)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb
```

**Comment by josephglanville** [comment]
Interesting, seen a few reports of `collect-debug-info` using lots of memory.
Will look at that soon, for now can you just gist the output of `flynn -a mariadb log`

**Comment by onnimonni** [comment]
This somewhat worked when I tried again. I sent both logs into logs@flynn.io.

**Comment by onnimonni** [comment]
I think it might be related to these which I found multiple times in the mariadb logs:
```
err="open /data/my.cnf: too many open files"
```

```
err="Error 1040: Too many connections"
```

How can I raise these limits?

**Comment by josephglanville** [comment]
@onnimonni I haven't had a chance to look into this yet but you can try raising the fd limit with
```
$ flynn -a mariadb limit set mariadb max_fd=100000
```
The default is 10k which is below the default maximum number of MySQL connections allowed so there is the potential for it to be hit, so we should probably fix that by itself.

Would you have an estimate of how many open connections you would have? If you could perchance have a look at netstat and see how many connections are connected to the MariaDB process that would be helpful information too.

**Comment by onnimonni** [comment]
I'm not sure how do I do that with netstat?

I tried this:
```
$ flynn -c production -a mariadb run sh
$ mysql
ERROR 1040 (HY000): Too many connections
```

**Comment by onnimonni** [comment]
And:

```
$ flynn -c production -a mariadb limit set mariadb max_fd=100000
sirenia cluster in unhealthy state (too few asyncs)
```

**Comment by onnimonni** [comment]
I forgot to mention that luckily I'm still using external mysql for all released applications in production. I wanted to try the mariadb appliance for a few new applications so this problem isn't critical.

Is it possible to just reset all mariadb appliances and start from beginning?

**Comment by onnimonni** [comment]
I think this only applies to my specific need because my mariadb appliances didn't yet have anything important in them but I fixed this by running:
```
$ flynn -c production -a mariadb scale mariadb=0
$ flynn -c production -a mariadb scale mariadb=0
$ ssh flynn-host-1
$ flynn-host fix --min-hosts=5
INFO[10-26|15:47:39] found expected hosts                     n=5
INFO[10-26|15:47:39] ensuring discoverd is running on all hosts
INFO[10-26|15:47:40] checking flannel
INFO[10-26|15:47:40] flannel looks good
INFO[10-26|15:47:40] waiting for discoverd to be available
INFO[10-26|15:47:40] checking for running controller API
INFO[10-26|15:47:40] found running controller API instances   n=2
INFO[10-26|15:47:40] found controller instance, checking critical formations
INFO[10-26|15:47:40] checking status of sirenia databases
INFO[10-26|15:47:40] checking for database state              db=postgres
INFO[10-26|15:47:40] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[10-26|15:47:40] found running leader                     fn=FixSirenia service=postgres
INFO[10-26|15:47:40] found running instances                  fn=FixSirenia service=postgres count=3
INFO[10-26|15:47:40] getting sirenia status                   fn=FixSirenia service=postgres
INFO[10-26|15:47:40] cluster claims to be read-write          fn=FixSirenia service=postgres
INFO[10-26|15:47:40] checking for database state              db=mariadb
INFO[10-26|15:47:40] checking sirenia cluster status          fn=FixSirenia service=mariadb
INFO[10-26|15:47:40] no running leader                        fn=FixSirenia service=mariadb
INFO[10-26|15:47:40] found running instances                  fn=FixSirenia service=mariadb count=4
INFO[10-26|15:47:40] getting sirenia status                   fn=FixSirenia service=mariadb
INFO[10-26|15:47:40] getting service metadata                 fn=FixSirenia service=mariadb
INFO[10-26|15:47:40] getting primary job info                 fn=FixSirenia service=mariadb job.id=grid3.flynn.xxxxxxxxxxxxxxxxxx-6397b3c1-05ff-44e0-a9ba-0c5accc3d68a
INFO[10-26|15:47:40] getting sync job info                    fn=FixSirenia service=mariadb job.id=grid5.flynn.xxxxxxxxxxxxxxxxxx-b58043a9-0bec-4295-b921-71824af47a3a
INFO[10-26|15:47:40] terminating unassigned sirenia instances fn=FixSirenia service=mariadb
INFO[10-26|15:47:41] starting primary job                     fn=FixSirenia service=mariadb job.id=grid3.flynn.xxxxxxxxxxxxxxxxxx-da9f78bc-dc40-47d1-9ae4-694e8c0c1f2a
INFO[10-26|15:47:41] starting sync job                        fn=FixSirenia service=mariadb job.id=grid5.flynn.xxxxxxxxxxxxxxxxxx-6e8ca4fe-4ed3-46e2-b4c6-529320100488
INFO[10-26|15:47:41] waiting for instance to start            fn=FixSirenia service=mariadb job.id=grid3.flynn.xxxxxxxxxxxxxxxxxx-da9f78bc-dc40-47d1-9ae4-694e8c0c1f2a
INFO[10-26|15:47:41] waiting for cluster to come up read-write fn=FixSirenia service=mariadb
INFO[10-26|15:47:57] checking for database state              db=mongodb
INFO[10-26|15:47:57] checking sirenia cluster status          fn=FixSirenia service=mongodb
INFO[10-26|15:47:57] found running leader                     fn=FixSirenia service=mongodb
INFO[10-26|15:47:57] found running instances                  fn=FixSirenia service=mongodb count=3
INFO[10-26|15:47:57] getting sirenia status                   fn=FixSirenia service=mongodb
INFO[10-26|15:47:57] cluster claims to be read-write          fn=FixSirenia service=mongodb
INFO[10-26|15:47:57] checking for running controller API
INFO[10-26|15:47:57] found running controller API instances   n=2
INFO[10-26|15:47:57] found controller instance, checking critical formations
INFO[10-26|15:47:57] scheduler looks up, moving on
INFO[10-26|15:47:57] cluster fix complete
```

And after that it started working again.
