### ISSUE TITLE
Installer Not Working for AWS

### ISSUE THREAD

**Issue by taylorbrooks** [flynn/flynn#3643]
Using the `v20161108.0` release.

After entering my AWS IAM credentials and clicking "Launch", this is the stacktrace in the CLI:

Any thoughts?
````shell
pen http://localhost:50454 in your browser to continue.
INFO[11-07|22:33:15] Event: new_cluster:  
INFO[11-07|22:33:15] Event: log: Creating key pair 
panic: reflect: call of reflect.Value.NumField on uint8 Value

goroutine 78 [running]:
panic(0x727620, 0xc42046a060)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x1a1
reflect.flag.mustBe(0x88, 0x19)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/util/_toolchain/go/src/reflect/value.go:201 +0xae
reflect.Value.NumField(0x6f2ee0, 0xc420438089, 0x88, 0xf8a100)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/util/_toolchain/go/src/reflect/value.go:1152 +0x34
github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws.(*EC2Client).loadStruct(0xc420270f00, 0xc4201400c0, 0x6f2ee0, 0xc420438089, 0x88, 0xc42046a040, 0x13, 0xc4205a7170, 0x23f114)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws/ec2.go:123 +0xe0
github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws.(*EC2Client).loadValues(0xc420270f00, 0xc4201400c0, 0x6f2ee0, 0xc420438089, 0xc42046a040, 0x13, 0x188, 0xc42046a040)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws/ec2.go:114 +0x2af
github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws.(*EC2Client).loadValues(0xc420270f00, 0xc4201400c0, 0x6ea340, 0xc42046a020, 0x6f4b17, 0x11, 0xf8a100, 0x6ea340)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws/ec2.go:107 +0x18e
github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws.(*EC2Client).loadStruct(0xc420270f00, 0xc4201400c0, 0x77ff40, 0xc420140000, 0x199, 0x0, 0x0, 0xc4202c2018, 0xc4202c2001)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws/ec2.go:170 +0x465
github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws.(*EC2Client).loadValues(0xc420270f00, 0xc4201400c0, 0x6cf1a0, 0xc420140000, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws/ec2.go:114 +0x2af
github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws.(*EC2Client).Do(0xc420270f00, 0x7feeb9, 0xd, 0x7f9afd, 0x4, 0x7f90b6, 0x1, 0x6cf1a0, 0xc420140000, 0x6cf1e0, ...)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/aws/ec2.go:27 +0x234
github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/gen/ec2.(*EC2).ImportKeyPair(0xc4201920e0, 0xc420140000, 0xc4205a7a28, 0xf4744, 0xc4203fc008)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/vendor/github.com/awslabs/aws-sdk-go/gen/ec2/ec2.go:1700 +0xc7
github.com/flynn/flynn/installer.(*AWSCluster).createKeyPair.func1(0x826299e00, 0xc4201c60c0)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/installer/aws_cluster.go:291 +0x131
github.com/flynn/flynn/installer.(*AWSCluster).wrapRequest(0xc420157110, 0xc4205a7d08, 0x1fc, 0x1fc)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/installer/aws_cluster.go:76 +0x77
github.com/flynn/flynn/installer.(*AWSCluster).createKeyPair(0xc420157110, 0xc420339668, 0xc420339678)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/installer/aws_cluster.go:293 +0x315
github.com/flynn/flynn/installer.(*AWSCluster).(github.com/flynn/flynn/installer.createKeyPair)-fm(0xc400000008, 0xcd0058)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/installer/aws_cluster.go:155 +0x2a
github.com/flynn/flynn/installer.(*AWSCluster).Run.func1(0xc420157110)
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/installer/aws_cluster.go:167 +0x2b1
created by github.com/flynn/flynn/installer.(*AWSCluster).Run
	/tmp/tmp.nOVWxTF3Rz/src/github.com/flynn/flynn/installer/aws_cluster.go:181 +0x3f
````

**Comment by taylorbrooks** [comment]
Do I need to update the CLI client to take advantage of this fix?

**Comment by jvatic** [comment]
Yes, you'll need to wait for the next [nightly](https://releases.flynn.io/#ch-nightly) build though.

As a workaround you can upload a keypair to EC2 and put the public and private key files in `~/.flynn/installer/keys` as `flynn.pub` and `flynn`.

**Comment by taylorbrooks** [comment]
How often are new builds released?

**Comment by josephglanville** [comment]
Nightly builds as the name implies are released nightly assuming the master branch passes CI.
Stable builds are released once a month.

You can check out the latest releases at https://releases.flynn.io/

**Comment by taylorbrooks** [comment]
This bug was found in the `v20161108.0` release. Looks like that's what nightly is currently at.

**Comment by taylorbrooks** [comment]
Ahh looks like the build is failing: https://ci.flynn.io/builds/20161109130940-65dcd139
