### ISSUE TITLE
Cannot set temp_disk limit

### ISSUE THREAD

**Issue by nusnewob** [flynn/flynn#3706]
I'm having an issue with my app use local disk as download cache, the app keep crashing and reports `No space left on device`
```
Traceback (most recent call last):
  File "/app/.heroku/python/bin/myapp", line 9, in <module>
    load_entry_point('myapp', 'console_scripts', 'myapp')()
  File "/app/myapp/cli.py", line 60, in main
    return func(*sys.argv[3:])
  File "/app/myapp/sync/ch/main.py", line 76, in main
    csv_paths = download.extract(download.zips(download.filenames()))
  File "/app/myapp/sync/ch/download.py", line 38, in zips
    zip_fh.write(zip_resp.content)
OSError: [Errno 28] No space left on device
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```
I'm running Flynn version `v20161114.0`
```
$ flynn-host version
v20161114.0
```

I've tried to set `temp_disk` limit on myapp,
```
$ flynn limit set worker temp_disk=2GB
invalid resource limit type: ["temp_disk" "2GB"]
$ flynn limit set worker temp_disk=2147483648
invalid resource limit type: ["temp_disk" "2147483648"]
```

Then I logged into the container, noticed this,
```
flynn@801c12d6-799f-4bc4-af0a-155a0aff8c79:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          97M  1.6M   96M   2% /
tmpfs           2.0G     0  2.0G   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/xvda1       40G  5.7G   32G  16% /.containerinit
flynn@801c12d6-799f-4bc4-af0a-155a0aff8c79:~$ mount
overlay on / type overlay (rw,relatime,lowerdir=/var/lib/flynn/volumes/zfs/mnt/squashfs/76f6b3bf39925b3b9140701aa6920eb32021dbbe15045bc6af388b67154dad3d:/var/lib/flynn/volumes/zfs/mnt/squashfs/18962e0ce642ebcdb47b50e63c94d439141ce86a77d9d923e90ea0fd3cfc13e5:/var/lib/flynn/volumes/zfs/mnt/squashfs/4c1cc7b8a1a83a1ecc0cde8ab6ec0e41b8e718d6f964486244952d99d329f201:/var/lib/flynn/volumes/zfs/mnt/squashfs/7e815919b7a6c176ed286f20a06dfb038167be2a66d8faa0649e68c80df0d97c,upperdir=/var/lib/flynn/volumes/zfs/mnt/ext2/ip10146127-801c12d6-799f-4bc4-af0a-155a0aff8c79/overlay-upperdir,workdir=/var/lib/flynn/volumes/zfs/mnt/ext2/ip10146127-801c12d6-799f-4bc4-af0a-155a0aff8c79/overlay-workdir)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
/dev/xvda1 on /.containerinit type ext4 (ro,relatime,discard,data=ordered)
/dev/xvda1 on /etc/resolv.conf type ext4 (ro,relatime,discard,data=ordered)
/dev/xvda1 on /etc/hosts type ext4 (rw,relatime,discard,data=ordered)
/dev/xvda1 on /.container-shared type ext4 (rw,relatime,discard,data=ordered)
/dev/xvda1 on /.containerconfig type ext4 (ro,relatime,discard,data=ordered)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,mode=755)
flynn@801c12d6-799f-4bc4-af0a-155a0aff8c79:~$ dd if=/dev/zero of=/tmp/test bs=1M count=100
dd: error writing ‘/tmp/test’: No space left on device
95+0 records in
94+0 records out
99540992 bytes (100 MB) copied, 0.175282 s, 568 MB/s
```

Then I compared it to my the other Flynn cluster running an older version `v20161017.1`,
```
nobody@3d50954d-0da7-48a4-8813-6d6e417a2e45:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
none             40G   21G   18G  55% /
tmpfs           2.0G     0  2.0G   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/xvda1       40G   21G   18G  55% /.containerinit
```

**Comment by lmars** [comment]
@nusnewob what version of the Flynn CLI are you using (check `flynn version`)? If it is older than `v20161114.0`, run `flynn update` and then try setting the limit again.

**Comment by nusnewob** [comment]
```
$ flynn version
v20161031.0
```

**Comment by lmars** [comment]
Ok, run `flynn update` and then try setting the limit again.

**Comment by nusnewob** [comment]
Yes, it does help, I can set the limit now, but it does't fix the issue the `temp_disk` are not used in the container,
```
$ flynn update
Updated v20161031.0 -> v20161116.0.
$ flynn limit set worker temp_disk=2GB
Created release bbafd123-697e-47df-8860-2f95ba0d256d
$ flynn -c datahub-staging limit
sync:    cpu=1000  max_fd=10000  memory=1GB  temp_disk=2GB
web:     cpu=1000  max_fd=10000  memory=1GB  temp_disk=2GB
worker:  cpu=1000  max_fd=10000  memory=1GB  temp_disk=2GB
$ flynn -c datahub-staging run bash
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          97M  1.6M   96M   2% /
tmpfs           2.0G     0  2.0G   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/xvda1       40G  7.9G   30G  21% /.containerinit
flynn@26d6b330-e288-4ceb-82d8-443d7b67f846:~$ dd if=/dev/zero of=/tmp/test bs=1M count=100
dd: error writing ‘/tmp/test’: No space left on device
95+0 records in
94+0 records out
99540992 bytes (100 MB) copied, 0.178088 s, 559 MB/s
```

**Comment by lmars** [comment]
@nusnewob you are setting the limit on the `worker` type, which does not apply to jobs started with `flynn run`.

Flynn currently doesn't support setting limits for `run` jobs (see #3707 for adding that), but you should find that your worker has the correct limits.

To demonstrate:

```
$ cat Procfile 
worker: df -h / && sleep 60

$ flynn log -t worker
2016-11-18T13:14:51.578541Z app[worker.host0-d6038a30-4b82-4d9e-a227-15b19fc6f9ef]: Filesystem      Size  Used Avail Use% Mounted on
2016-11-18T13:14:51.578602Z app[worker.host0-d6038a30-4b82-4d9e-a227-15b19fc6f9ef]: overlay          97M  1.6M   96M   2% /

$ flynn limit set worker temp_disk=2GB
Created release 5c9ed105-c5a1-410e-9670-6e1f527737a5

$ flynn log -t worker
2016-11-18T13:14:51.578541Z app[worker.host0-d6038a30-4b82-4d9e-a227-15b19fc6f9ef]: Filesystem      Size  Used Avail Use% Mounted on
2016-11-18T13:14:51.578602Z app[worker.host0-d6038a30-4b82-4d9e-a227-15b19fc6f9ef]: overlay          97M  1.6M   96M   2% /
2016-11-18T13:15:05.328925Z app[worker.host0-c0a8d91c-681b-482d-9666-06cc8863081c]: Filesystem      Size  Used Avail Use% Mounted on
2016-11-18T13:15:05.328968Z app[worker.host0-c0a8d91c-681b-482d-9666-06cc8863081c]: overlay         2.0G  3.1M  2.0G   1% /
```

**Comment by nusnewob** [comment]
Thanks, I'll close the issue now.
