### ISSUE TITLE
Restore failure on recently migrated endpoint

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3822]
I recently upgraded this endpoint to test migration from 14.04 to 16.04. The backups have doubled in size since before the migration, and (more importantly) the first restore hit the following error:

```
++ flynn-host bootstrap --peer-ips=10.110.88.3,10.110.131.235,10.110.196.167 --from-backup /mnt/flynn-restore-source --timeout 3600
+ bootstrap_output='panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0xa58280, 0xc4203010d0)
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x1a1
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc420017830, 0x0, 0x0, 0x0, 0xa58280, 0xc4203010d0)
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x222
github.com/flynn/flynn/pkg/shutdown.Exit()
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x6a
panic(0xa58280, 0xc4203010d0)
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:458 +0x243
github.com/flynn/flynn/host/cli.runBootstrapBackup.func2(0xc4202187e0, 0xc420231740)
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/host/cli/bootstrap.go:247 +0x204
github.com/flynn/flynn/host/cli.runBootstrapBackup(0xc420254000, 0x9deb, 0x9feb, 0x7ffc04bb9860, 0x19, 0xc420218420, 0x0, 0x0, 0xc4202263c0, 0x3, ...)
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/host/cli/bootstrap.go:268 +0xd2ab
github.com/flynn/flynn/host/cli.runBootstrap(0xc4201f55c0, 0x226, 0xc42005f3e0)
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/host/cli/bootstrap.go:120 +0x612
github.com/flynn/flynn/host/cli.Run(0x7ffc04bb9813, 0x9, 0xc42007b480, 0x5, 0x8, 0xc42004bc01, 0xb7f610)
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x4b4
main.main()
        /tmp/tmp.2C8TIsBXaF/src/github.com/flynn/flynn/host/host.go:155 +0x4d4'
```

https://gist.github.com/3dc460e283b48aca703ef5bd2db3f449 is the debug-info gathered. I am trying again to see if this repeats.

**Comment by temujin9** [comment]
It does repeat: https://gist.github.com/5c4522e7aeadd302a1e00293ac3ae5df

**Comment by lmars** [comment]
@temujin9 what version of Flynn are you bootstrapping? I can't see how that code would panic unless you are using an old bootstrap manifest.

**Comment by temujin9** [comment]
I'm using `FLYNN_VERSION="v20170109.0"` here.

**Comment by titanous** [comment]
Are you still encountering this issue with `v20170121.0`?

**Comment by RobinDaugherty** [comment]
Experiencing the same issue, using `v20170116.0p2` with a backup that was created with `v20161218.1`.

**Comment by titanous** [comment]
@RobinDaugherty can you post the exact error output?

**Comment by RobinDaugherty** [comment]
I don't see anything in the release notes that addresses backup restoration since `v20170116.0p2`. @titanous are you asking about `v20170121.0` because there's something in that release that may fix it? I just haven't wanted to go beyond the latest stable without a good reason.

**Comment by RobinDaugherty** [comment]
```
panic: assignment to entry in nil map [recovered]
    panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0xa58300, 0xc4202ef270)
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x1a1
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc420063830, 0x0, 0x0, 0x0, 0xa58300, 0xc4202ef270)
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x222
github.com/flynn/flynn/pkg/shutdown.Exit()
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x6a
panic(0xa58300, 0xc4202ef270)
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:458 +0x243
github.com/flynn/flynn/host/cli.runBootstrapBackup.func2(0xc42020a780, 0xc4202254c0)
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/cli/bootstrap.go:247 +0x204
github.com/flynn/flynn/host/cli.runBootstrapBackup(0xc420242000, 0x9e33, 0xa033, 0x7ffd5878c84c, 0x17, 0xc42020a3c0, 0x0, 0x0, 0xc42023e240, 0x3, ...)
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/cli/bootstrap.go:268 +0xd2b0
github.com/flynn/flynn/host/cli.runBootstrap(0xc4201e3680, 0x226, 0xc42008fb30)
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/cli/bootstrap.go:120 +0x612
github.com/flynn/flynn/host/cli.Run(0x7ffd5878c834, 0x9, 0xc4201176c0, 0x4, 0x4, 0xc420045c01, 0xb7fcc0)
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x4b4
main.main()
    /tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/host.go:155 +0x4d4
```

**Comment by titanous** [comment]
@RobinDaugherty yes, there were a couple fixes that might be related, please try the latest nightly:

https://github.com/flynn/flynn/commit/327da97802f847edf9460bd7874caa16075cc5ee
https://github.com/flynn/flynn/commit/ec7698ca7562df7b71a51b57e388999812aa8b28

**Comment by RobinDaugherty** [comment]
On version `v20170207.0`:

```
panic: assignment to entry in nil map [recovered]
    panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0xa5ae40, 0xc4203085f0)
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x1a1
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc420017860, 0x0, 0x0, 0x0, 0xa5ae40, 0xc4203085f0)
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x222
github.com/flynn/flynn/pkg/shutdown.Exit()
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x6a
panic(0xa5ae40, 0xc4203085f0)
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:458 +0x243
github.com/flynn/flynn/host/cli.runBootstrapBackup.func2(0xc4200d7f80, 0xc420195e80)
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/host/cli/bootstrap.go:247 +0x204
github.com/flynn/flynn/host/cli.runBootstrapBackup(0xc420254000, 0x9deb, 0x9feb, 0x7ffd916e67b3, 0x17, 0xc4200d7bc0, 0x0, 0x0, 0xc420169290, 0x3, ...)
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/host/cli/bootstrap.go:268 +0xd2e7
github.com/flynn/flynn/host/cli.runBootstrap(0xc4201fd440, 0x226, 0xc4200e2a50)
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/host/cli/bootstrap.go:120 +0x612
github.com/flynn/flynn/host/cli.Run(0x7ffd916e679b, 0x9, 0xc4200dbe40, 0x4, 0x4, 0xc420047c01, 0xb82fb8)
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x4b4
main.main()
    /tmp/tmp.rJNe8qvsER/src/github.com/flynn/flynn/host/host.go:156 +0x4d4
```

**Comment by titanous** [comment]
@RobinDaugherty Would you please extract `flynn.json` from the backup (a gzipped tarball) and email it to logs@flynn.io? Ideally redact any keys you see in there before sending it.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
