### ISSUE TITLE
Inline update failed, now everything is hanging

### ISSUE THREAD

**Issue by scottrobertson** [flynn/flynn#3889]
Hey

I performed an inline upgrade and the following error happened:

```
INFO[01-28|18:21:58] starting deploy of system app name=controller EROR[01-28|18:24:17] error deploying app name=controller err="timed out waiting for job events: map[web:map[down:1]]" 
```

I ran upgrade again, and now it's just hanging on:

```
checking host version compatibility
```

Cannot get which version I am running because the upgrader already updated the flynn-host binary with the new versions.

Backups are also hanging too. I assume a service is down and is timing out.

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug-info` and post the logs here.

**Comment by scottrobertson** [comment]
Log collection is running now, takes a while from what I remember

**Comment by scottrobertson** [comment]
I had to collect them manually. I have emailed them across.

**Comment by scottrobertson** [comment]
Potentially related to https://github.com/flynn/flynn/issues/3792 (i have had issues in the past, just didnt seem related)

**Comment by scottrobertson** [comment]
Running `flynn-host fix` this time however just hangs:

```
INFO[01-28|19:16:44] found expected hosts                     n=3
INFO[01-28|19:16:44] ensuring discoverd is running on all hosts
```

**Comment by scottrobertson** [comment]
For @titanous 

```
PC=0x499591 m=0

goroutine 0 [idle]:
runtime.futex(0x1039ad0, 0x0, 0x0, 0x0, 0x0, 0xc420222140, 0x0, 0x0, 0x7ffdbfcda8b0, 0x44cbb2, ...)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/sys_linux_amd64.s:387 +0x21
runtime.futexsleep(0x1039ad0, 0x0, 0xffffffffffffffff)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0x1039ad0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/lock_futex.go:145 +0x82
runtime.stopm()
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:1594 +0xad
runtime.findrunnable(0xc42001ea00, 0x0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:2021 +0x228
runtime.schedule()
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:2120 +0x14c
runtime.park_m(0xc4201636c0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:2183 +0x123
runtime.mcall(0x7ffdbfcdaa50)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:240 +0x5b

goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0xc420158500, 0xc4202302a0, 0x0, 0x0, 0x0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1840 +0x93b
net/http.(*Transport).RoundTrip(0xc4200d60f0, 0xc4201b6690, 0xc4200d60f0, 0x0, 0x0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:380 +0x4ee
net/http.send(0xc4201b6690, 0x1017e20, 0xc4200d60f0, 0x0, 0x0, 0x0, 0x8, 0xc420217068, 0xc420150828)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0x1038620, 0xc4201b6690, 0x0, 0x0, 0x0, 0xc420150828, 0x0, 0x1)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0x1038620, 0xc4201b6690, 0xb7f078, 0x3, 0xc4201b6601, 0x0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Do(0x1038620, 0xc4201b6690, 0x3, 0xc4201dd020, 0x23)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/client.go:184 +0x1ea
github.com/flynn/flynn/pkg/httpclient.(*Client).rawReq(0xc42014adc0, 0xb0a279, 0x3, 0xc4201dd020, 0x23, 0xc4201dcff0, 0x0, 0x0, 0xa08ec0, 0xc420150810, ...)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/httpclient/json.go:106 +0x126
github.com/flynn/flynn/pkg/httpclient.(*Client).RawReqWithHTTP(0xc42014adc0, 0xb0a279, 0x3, 0xb0d8f1, 0xa, 0xc4201dcff0, 0x0, 0x0, 0xa08ec0, 0xc420150810, ...)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/httpclient/json.go:88 +0xf2
github.com/flynn/flynn/pkg/httpclient.(*Client).RawReq(0xc42014adc0, 0xb0a279, 0x3, 0xb0d8f1, 0xa, 0xc4201dcff0, 0x0, 0x0, 0xa08ec0, 0xc420150810, ...)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/httpclient/json.go:81 +0xb0
github.com/flynn/flynn/pkg/httpclient.(*Client).Send(0xc42014adc0, 0xb0a279, 0x3, 0xb0d8f1, 0xa, 0x0, 0x0, 0xa08ec0, 0xc420150810, 0x1, ...)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/httpclient/json.go:231 +0x175
github.com/flynn/flynn/pkg/httpclient.(*Client).Get(0xc42014adc0, 0xb0d8f1, 0xa, 0xa08ec0, 0xc420150810, 0xc42014ae60, 0xc4201dbff8)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/httpclient/json.go:247 +0x84
github.com/flynn/flynn/pkg/cluster.(*Host).ListJobs(0xc4202301c0, 0xc420230180, 0x3, 0x3)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/cluster/host.go:95 +0x7a
github.com/flynn/flynn/host/cli.jobList(0xc4201dbdc0, 0xc4201dca00, 0xb0ab2e, 0x5, 0xc420193caa, 0x0, 0x1)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/cli/ps.go:70 +0xb2
github.com/flynn/flynn/host/cli.runPs(0xc4201dbd80, 0xc4201dbdc0, 0xc42014fe90, 0x1)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/cli/ps.go:33 +0x9d
github.com/flynn/flynn/host/cli.Run(0x7ffdbfcdc8d3, 0x2, 0x10555c8, 0x0, 0x0, 0xc420051c01, 0xb7fcc0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/cli/cli.go:57 +0x3ca
main.main()
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/host/host.go:155 +0x4d4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc420013890)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x117
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xc3

goroutine 18 [select, locked to thread]:
runtime.gopark(0xb7f550, 0x0, 0xb0b7f6, 0x6, 0x18, 0x2)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420028730, 0x0, 0x18)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420028730)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 53 [select]:
net/http.(*persistConn).writeLoop(0xc420158500)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1063 +0x50e

goroutine 50 [IO wait]:
net.runtime_pollWait(0x7f2ede5b2278, 0x72, 0x4)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201ebb80, 0x72, 0xc42003d9d0, 0xc420010268)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201ebb80, 0x101a420, 0xc420010268)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201ebb20, 0xc420220000, 0x1000, 0x1000, 0x0, 0x101a420, 0xc420010268)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42021c000, 0xc420220000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420158400, 0xc420220000, 0x1000, 0x1000, 0x52f6e0, 0xc42003db58, 0x442ccd)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc42021e000)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc42021e000, 0x1, 0xc42003dbbd, 0x1, 0x0, 0xc42021e060, 0x0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420158400)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1062 +0x4e9

goroutine 51 [select]:
net/http.(*persistConn).writeLoop(0xc420158400)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1646 +0x3bd
created by net/http.(*Transport).dialConn
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1063 +0x50e

goroutine 52 [IO wait]:
net.runtime_pollWait(0x7f2ede5b21b8, 0x72, 0x6)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4201ebe90, 0x72, 0xc42003c9d0, 0xc420010268)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4201ebe90, 0x101a420, 0xc420010268)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc4201ebe30, 0xc420234000, 0x1000, 0x1000, 0x0, 0x101a420, 0xc420010268)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc42021c008, 0xc420234000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/net.go:173 +0x70
net/http.(*persistConn).Read(0xc420158500, 0xc420234000, 0x1000, 0x1000, 0x5275f3, 0xc420186b78, 0xc420186b88)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1261 +0x154
bufio.(*Reader).fill(0xc42021e180)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Peek(0xc42021e180, 0x1, 0xc42021e300, 0xc420186c60, 0x44c79c, 0xc420185138, 0x1)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:129 +0x62
net/http.(*persistConn).readLoop(0xc420158500)
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1418 +0x1a1
created by net/http.(*Transport).dialConn
	/tmp/tmp.225plNbtkw/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/transport.go:1062 +0x4e9

rax    0xca
rbx    0x1038d70
rcx    0x499593
rdx    0x0
rdi    0x1039ad0
rsi    0x0
rbp    0x7ffdbfcda880
rsp    0x7ffdbfcda838
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xf3
r14    0x8
r15    0x3
rip    0x499591
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
