### ISSUE TITLE
nil panic in logmux SinkManager

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3895]
```text
Jan 31 19:28:14 ip-10-110-170-150 flynn-host[1924]: t=2017-01-31T19:28:11+0000 lvl=eror msg="heartbeat failed" component=discoverd service=flynn-host addr=10.110.170.150:1113 err="Error sending HTTP request, errors: service_unavailable: discoverd: no known leader,service_unavailable: discoverd: no known leader,service_unavailable: discoverd: no known leader"
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5b2596]
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]: goroutine 2157 [running]:
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]: panic(0xa59060, 0xc42000e040)
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]:         /tmp/tmp.pbr3vQuQhZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x1a1
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]: github.com/flynn/flynn/host/logmux.(*LogAggregatorSink).Close(0xc4209796c0)
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]:         /tmp/tmp.pbr3vQuQhZ/src/github.com/flynn/flynn/host/logmux/sink.go:422 +0x26
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]: github.com/flynn/flynn/host/logmux.(*Mux).addSink(0xc4200f5580, 0x1024100, 0xc4209796c0)
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]:         /tmp/tmp.pbr3vQuQhZ/src/github.com/flynn/flynn/host/logmux/logmux.go:115 +0x2ba
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]: created by github.com/flynn/flynn/host/logmux.(*SinkManager).addSink
Jan 31 19:37:56 ip-10-110-170-150 flynn-host[1924]:         /tmp/tmp.pbr3vQuQhZ/src/github.com/flynn/flynn/host/logmux/sink.go:288 +0x13e
```

/cc @josephglanville @temujin9

**Comment by josephglanville** [comment]
@lmars was this fixed by #3832? If not I can have a look at it today.
