### ISSUE TITLE
Postgres cluster does not recover from node failure

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#4024]
After a node was rebooted the cluster never returned to normal operation. I attempted `flynn-host fix` however this never completed.

After a little probing, it appears that the postgres cluster is the issue. There are two nodes running, which acording to @lmars's comment in a previous issue with a similar situation.

The two nodes fail to form a cluster however:

```
t=2017-04-04T04:54:08+0000 lvl=dbug msg="starting database" app=postgres component=peer fn=applyConfig
t=2017-04-04T04:54:08+0000 lvl=info msg="starting up as standby" app=postgres component=postgres fn=assumeStandby upstream=100.100.80.37:5432
t=2017-04-04T04:54:08+0000 lvl=info msg="waiting for upstream to come online" app=postgres component=postgres fn=waitForUpstream upstream=100.100.80.37:5432
t=2017-04-04T04:54:38+0000 lvl=eror msg="error getting upstream status" app=postgres component=postgres fn=waitForUpstream upstream=100.100.80.37:5432 err="Get http://100.100.80.37:5433/status: dial tcp 100.100.80.37:5433: i/o timeout"
t=2017-04-04T04:54:38+0000 lvl=eror msg="upstream did not come online in time" app=postgres component=postgres fn=waitForUpstream upstream=100.100.80.37:5432
t=2017-04-04T04:54:38+0000 lvl=eror msg="error applying database config" app=postgres component=peer fn=applyConfig err="upstream is offline"
t=2017-04-04T04:54:38+0000 lvl=info msg="reconfiguring database" app=postgres component=peer fn=applyConfig
```

```
t=2017-04-04T04:54:34+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
t=2017-04-04T04:54:34+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
t=2017-04-04T04:54:34+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
t=2017-04-04T04:54:34+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
```
Running `flynn-host list` shows all nodes (6 of them) online with an elected leader.

**Comment by thomasfedb** [comment]
This is running with `flynn-host` version `v20170217.0`.

**Comment by lmars** [comment]
@thomasfedb did the node come back with the same IP and hostname?

**Comment by thomasfedb** [comment]
Hi @lmars, yes same IP and same hostname.

**Comment by thomasfedb** [comment]
It's now trying to start the controller, basically staring and endless chain of jobs that all crash with this:

```
panic: dial tcp 100.100.80.37:5432: getsockopt: connection refused [recovered]
	panic: dial tcp 100.100.80.37:5432: getsockopt: connection refused

goroutine 1 [running]:
panic(0x7ea0e0, 0xc420480b40)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x1a1
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc420015d10, 0x0, 0x0, 0x0, 0x7ea0e0, 0xc420480b40)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x222
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x6a
panic(0x7ea0e0, 0xc420480b40)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:458 +0x243
github.com/flynn/flynn/pkg/postgres.Wait(0xc42001af50, 0x0, 0xa)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/pkg/postgres/postgres.go:83 +0x551
main.main()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/controller/controller.go:61 +0x136
```
