### ISSUE TITLE
panic in go9p during build

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#4092]
```text
23:48:15.419: dashboard-builder: └── sass-graph@2.2.2 (glob@7.1.1, scss-tokenizer@0.2.1, yargs@6.6.0, lodash@4.17.4)
23:48:15.454: dashboard-builder: + go build -o /bin/dashboard-compile github.com/flynn/flynn/dashboard/app
29 / 38 [====================================================================================>--------------------------] 76.32 % 1m56spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x29 pc=0x588d05]

goroutine 408201 [running]:
panic(0x805ea0, 0xc42000e030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/flynn/flynn/vendor/github.com/rminnich/go9p.(*SrvReq).PostProcess(0xc42017c120)
	/go/src/github.com/flynn/flynn/vendor/github.com/rminnich/go9p/srv_srv.go:346 +0x1b5
github.com/flynn/flynn/vendor/github.com/rminnich/go9p.(*SrvReq).Respond(0xc42017c120)
	/go/src/github.com/flynn/flynn/vendor/github.com/rminnich/go9p/srv_srv.go:418 +0x20e
github.com/flynn/flynn/vendor/github.com/rminnich/go9p.(*Srv).flush(0xc42020a9a0, 0xc42017c1e0)
	/go/src/github.com/flynn/flynn/vendor/github.com/rminnich/go9p/srv_fcall.go:171 +0x1bb
github.com/flynn/flynn/vendor/github.com/rminnich/go9p.(*SrvReq).Process(0xc42017c1e0)
	/go/src/github.com/flynn/flynn/vendor/github.com/rminnich/go9p/srv_srv.go:290 +0x1cf
github.com/flynn/flynn/vendor/github.com/rminnich/go9p.(*SrvReq).process(0xc42017c1e0)
	/go/src/github.com/flynn/flynn/vendor/github.com/rminnich/go9p/srv_srv.go:245 +0x12e
created by github.com/flynn/flynn/vendor/github.com/rminnich/go9p.(*Conn).recv
	/go/src/github.com/flynn/flynn/vendor/github.com/rminnich/go9p/srv_conn.go:160 +0x497
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by titanous** [comment]
This is happening repeatably on every try, though at different points in the build.
