### ISSUE TITLE
another rails app webpack error

### ISSUE THREAD

**Issue by williamhatch** [flynn/flynn#4444]
Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       NoMethodError: undefined method `to_sym' for nil:NilClass
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/braintree-2.72.0/lib/braintree/configuration.rb:61:in `environment='
       /tmp/build/app/config/environments/production.rb:112:in `block in <top (required)>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/railtie.rb:209:in `instance_eval'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/railtie.rb:209:in `configure'
       /tmp/build/app/config/environments/production.rb:1:in `<top (required)>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:599:in `each'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/engine.rb:599:in `block in <class:Engine>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `run'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:44:in `each'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/application.rb:352:in `initialize!'
       /tmp/build/app/config/environment.rb:5:in `<top (required)>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-5.0.1/lib/rails/application.rb:448:in `block in run_tasks_blocks'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => environment
       (See full trace by running task with --trace)

**Comment by williamhatch** [comment]
lib/tasks/assets.rake

Rake::Task["assets:precompile"].clear
   namespace :assets do
     task 'precompile' do
     puts "Not pre-compiling assets..."
   end
end

using this to skip precompile.. it works!
