### ISSUE TITLE
Backup fails with "slice bounds of range"

### ISSUE THREAD

**Issue by denisvmedia** [flynn/flynn#4457]
This is what I'm getting:

```
C:\Users\user\Documents>flynn cluster backup --file backup.tar
0 B                                                                                                                                                                                                      Creating cluster backup...
2.60 GB 9.22 MB/s                                                                                                                                                                                        panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0x113c6980, 0x0, 0x0, 0x0, 0x750140, 0x98bfc0)
        /go/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x182
github.com/flynn/flynn/pkg/shutdown.Exit()
        /go/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x57
panic(0x750140, 0x98bfc0)
        /usr/local/go/src/runtime/panic.go:491 +0x1d0
archive/tar.(*Writer).Write(0x1155e000, 0x117c8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/archive/tar/writer.go:337 +0x162
io.copyBuffer(0x95dfd0, 0x114d1560, 0x95e650, 0x113d7980, 0x117c8000, 0x8000, 0x8000, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/io/io.go:394 +0x192
io.Copy(0x95dfd0, 0x114d1560, 0x95e650, 0x113d7980, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:362 +0x51
github.com/flynn/flynn/pkg/backup.(*TarWriter).WriteCommandOutput(0x114d1560, 0x9663e0, 0x114e0078, 0x79da99, 0xf, 0x79ae2a, 0x8, 0x11558580, 0x0, 0x0)
        /go/src/github.com/flynn/flynn/pkg/backup/tar_writer.go:100 +0x491
github.com/flynn/flynn/pkg/backup.Run(0x9663e0, 0x114e0078, 0x95e670, 0x114e0088, 0x95feb0, 0x115560a0, 0x0, 0x0)
        /go/src/github.com/flynn/flynn/pkg/backup/backup.go:37 +0x59c
main.runClusterBackup(0x1146cca0, 0x0, 0x0)
        /go/src/github.com/flynn/flynn/cli/cluster.go:430 +0x15f
main.runCluster(0x1146cca0, 0x0, 0x0)
        /go/src/github.com/flynn/flynn/cli/cluster.go:123 +0x4fe
main.runCommand(0x11318098, 0x7, 0x113c73e0, 0x3, 0x4, 0x1, 0x7f1760)
        /go/src/github.com/flynn/flynn/cli/main.go:178 +0x26e
main.main()
        /go/src/github.com/flynn/flynn/cli/main.go:128 +0x516
```

Flynn cli version:

```
C:\Users\user\Documents>flynn version
v20181022.0-024ef2e
```

Please help.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
