### ISSUE TITLE
sqlalchemy dialects implementation

### ISSUE THREAD

**Issue by DaxterXS** [flynn/flynn#4582]
### Introduction
I'm using flynn to deploy an app that will automatically read a database and permorm some analysis, previously i used flynn reading a database [teiid] without dialects
Flynn Version : v20191122.0-04e0a8f
### Issue
Flynn can't use dialects from` sqlalchemy ` package dialects
### Reproduce
Prerequisites:
- Add `sqlalchemy` package in the `requirement.txt` file to be installed
- import `sqlalchemy` and the dialect needed example(oracle)

Result:
- **Expected**: Flynn finding the module and perform the connection
- **Actual**: Flynn has installed the module `sqlalchemy` and also the dialect because i can see the folder, but it doesn't have the dialect module installed
### Example
_INPUT_
```
import pandas as pd
import sqlalchemy
from sqlalchemy.dialects.mssql import pymssql
from sqlalchemy.dialects import oracle

def extract():
    engine = sqlalchemy.create_engine("oracle://{user}:{pwd}@{host}:{port}") 
    query = """
                SELECT *
                FROM database
    """
    df = pd.read_sql (query, engine)
    return df
def data_extraction():
    print(sqlalchemy.dialects.oracle)
    print(sqlalchemy.dialects)
    print(sqlalchemy)
    print(extract().shape)
if __name__ == '__main__':
    data_extraction()
```
_OUTPUT_
```
 <module 'sqlalchemy.dialects.oracle' from '/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/dialects/oracle/__init__.py'>
 <module 'sqlalchemy.dialects' from '/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/dialects/__init__.py'>
 <module 'sqlalchemy' from '/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/__init__.py'>
 18:33:00 ModuleNotFoundError: No module named 'oracle'
  Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/worker.py", line 793, in perform_job
  rv = job.perform()
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 599, in perform
  self._result = self._execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/rq/job.py", line 605, in _execute
  return self.func(*self.args, **self.kwargs)
  File "/app/my_program.py", line 67, in data_extraction
  print(extract().shape)
  File "/app/my_program.py", line 27, in extract= sqlalchemy.create_engine("oracle://{user}:{pwd}@{host}:{port}")
   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 425, in create_engine
    return strategy.create(*args, **kwargs)
   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 81, in create
   dbapi = dialect_cls.dbapi(**dbapi_args)
   File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/dialects/oracle/oracle.py", line 62, in dbapi
   module = __import__('oracle)
  ModuleNotFoundError: No module named 'oracle'
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
